/**
 * @file The order commands list in: tab completion offers matches in this order.
 *
 * Kept explicitly, apart from which group registers a name, so registering the
 * core and a backend's commands separately does not reorder what the shell
 * offers. A name registered but not listed here lists after these, in
 * registration order.
 *
 * @module
 */

/** Help topics, which are also the `/bin` builtins and the completion candidates. */
export const HELP_ORDER: string[] = ["2048", "user", "sudo", "ls", "cd", "netstat", "pwd", "cat", "edit", "setfacl", "getfacl", "chmod", "setfattr", "getfattr", "rm", "cp", "mv", "touch", "config", "mkdir", "rmdir", "upload", "download", "connect", "logout", "plugin", "plugins", "feed", "feeds", "files", "links", "dirs", "pipeline", "pacs", "pacs query", "pacs pull", "pacs connect", "pacs disconnect", "pacs list", "pacsservers", "pacsqueries", "pacsretrieve", "exit", "context", "whoami", "version", "id", "fortune", "cowsay", "cowthink", "figlet", "banner", "lolcat", "rev", "tac", "yes", "seq", "factor", "primes", "shuf", "roll", "rot13", "morse", "calc", "units", "who", "uptime", "ping", "chrisfetch", "say", "wtf", "file", "xxd", "strings", "sha256sum", "md5sum", "qr", "pom", "stardate", "ddate", "sunrise", "timer", "leave", "stopwatch", "sl", "cmatrix", "rain", "asciiquarium", "tetris", "snake", "quiz", "hangman", "notes", "weather", "motd", "date", "cal", "whereami", "proc", "prompt", "physicalmode", "timing", "debug", "parametersofplugin", "tree", "du", "store", "compute", "tag", "tags", "record", "play", "expect", "gather", "group", "groups", "pluginmeta", "pluginmetas", "plugininstance", "plugininstances", "workflow", "workflows", "meta", "metas", "instance", "instances", "job", "jobs", "help", "!", "dcm", "image", "cubepath", "query", "pull"];

/** Names answered by an envelope handler. */
export const ENVELOPE_ORDER: string[] = ["2048", "cat", "cd", "cp", "mv", "rm", "setfacl", "getfacl", "chmod", "setfattr", "getfattr", "mkdir", "rmdir", "touch", "pwd", "netstat", "id", "whoami", "whereami", "timing", "physicalmode", "debug", "version", "fortune", "cowsay", "cowthink", "figlet", "banner", "lolcat", "rev", "tac", "yes", "seq", "factor", "primes", "shuf", "roll", "rot13", "morse", "calc", "units", "who", "uptime", "ping", "chrisfetch", "say", "wtf", "file", "xxd", "strings", "sha256sum", "md5sum", "qr", "pom", "stardate", "ddate", "sunrise", "timer", "leave", "stopwatch", "sl", "cmatrix", "rain", "asciiquarium", "tetris", "snake", "quiz", "hangman", "weather", "motd", "notes", "date", "cal", "ls", "tree", "du", "help", "proc", "logout", "cubepath", "dcm", "image", "query", "feed", "feeds", "compute", "computes", "tag", "tags", "expect", "play", "record", "gather", "group", "groups", "user", "users", "pluginmeta", "pluginmetas", "meta", "metas", "plugininstance", "plugininstances", "instance", "instances", "job", "jobs", "workflow", "workflows", "files", "links", "dirs", "context", "parametersofplugin", "plugin", "plugins", "pacsservers", "pacsqueries", "pacsretrieve", "connect", "upload", "download", "store", "edit", "config", "pacs", "pull", "pipeline", "pipelines"];

/** Names answered by a plain handler. */
export const PLAIN_ORDER: string[] = ["2048", "connect", "logout", "cd", "ls", "pwd", "netstat", "cat", "rm", "setfacl", "getfacl", "chmod", "setfattr", "getfattr", "cp", "mv", "touch", "mkdir", "rmdir", "upload", "pacs", "pipeline", "pipelines", "pull", "query", "cubepath", "dcm", "image", "download", "edit", "config", "context", "parametersofplugin", "physicalmode", "timing", "id", "whoami", "whereami", "debug", "fortune", "cowsay", "cowthink", "figlet", "banner", "lolcat", "rev", "tac", "yes", "seq", "factor", "primes", "shuf", "roll", "rot13", "morse", "calc", "units", "who", "uptime", "ping", "chrisfetch", "say", "wtf", "file", "xxd", "strings", "sha256sum", "md5sum", "qr", "pom", "stardate", "ddate", "sunrise", "timer", "leave", "stopwatch", "sl", "cmatrix", "rain", "asciiquarium", "tetris", "snake", "quiz", "hangman", "weather", "motd", "notes", "date", "cal", "help", "proc", "tree", "du", "store", "plugin", "plugins", "feed", "feeds", "compute", "computes", "tag", "tags", "expect", "play", "record", "gather", "group", "groups", "pluginmeta", "pluginmetas", "meta", "metas", "plugininstance", "plugininstances", "instance", "instances", "job", "jobs", "workflow", "workflows", "files", "links", "dirs", "pacsservers", "pacsqueries", "pacsretrieve"];
