/**
 * @file Bundled classic "fortune" cookies.
 *
 * Vendored from the traditional fortune-mod datfiles so the `fortune` builtin is
 * fully self-contained: no host files, no subprocess — it works identically in a
 * local shell, over a CALYPSO daemon, and in the standalone binary. This content
 * is classic BSD `fortune` material, freely distributed since the 1980s (BSD
 * lineage: Regents of the University of California / Ken Arnold and community
 * contributors).
 *
 * Regenerate with `node scripts/fortunes_generate.mjs`; do not edit by hand.
 *
 * @module
 */

/** The bundled fortune cookies, one entry per fortune. */
export const FORTUNES: readonly string[] = [
  "A day for firm decisions!!!!!  Or is it?",
  "A few hours grace before the madness begins again.",
  "A gift of a flower will soon be made to you.",
  "A long-forgotten loved one will appear soon.\n\nBuy the negatives at any price.",
  "A tall, dark stranger will have more fun than you.",
  "A visit to a fresh place will bring strange work.",
  "A visit to a strange place will bring fresh work.",
  "A vivid and creative mind characterizes you.",
  "Abandon the search for Truth; settle for a good fantasy.",
  "Accent on helpful side of your nature.  Drain the moat.",
  "Advancement in position.",
  "After your lover has gone you will still have PEANUT BUTTER!",
  "Afternoon very favorable for romance.  Try a single person for a change.",
  "Alimony and bribes will engage a large share of your wealth.",
  "All the troubles you have will pass away very quickly.",
  "Among the lucky, you are the chosen one.",
  "An avocado-tone refrigerator would look good on your resume.",
  "An exotic journey in downtown Newark is in your future.",
  "Another good night not to sleep in a eucalyptus tree.",
  "Are you a turtle?",
  "Are you ever going to do the dishes?  Or will you change your major to biology?",
  "Are you making all this up as you go along?",
  "Are you sure the back door is locked?",
  "Artistic ventures highlighted.  Rob a museum.",
  "Avert misunderstanding by calm, poise, and balance.",
  "Avoid gunfire in the bathroom tonight.",
  "Avoid reality at all costs.",
  "Bank error in your favor.  Collect $200.",
  "Be careful!  Is it classified?",
  "Be careful!  UGLY strikes 9 out of 10!",
  "Be cautious in your daily affairs.",
  "Be cheerful while you are alive.\n\t\t-- Phathotep, 24th Century B.C.",
  "Be different: conform.",
  "Be free and open and breezy!  Enjoy!  Things won't get any better so\nget used to it.",
  "Be security conscious -- National defense is at stake.",
  "Beauty and harmony are as necessary to you as the very breath of life.",
  "Best of all is never to have been born.  Second best is to die soon.",
  "Better hope the life-inspector doesn't come around while you have your\nlife in such a mess.",
  "Beware of a dark-haired man with a loud tie.",
  "Beware of a tall black man with one blond shoe.",
  "Beware of a tall blond man with one black shoe.",
  "Beware of Bigfoot!",
  "Beware of low-flying butterflies.",
  "Beware the one behind you.",
  "Blow it out your ear.",
  "Break into jail and claim police brutality.",
  "Bridge ahead.  Pay troll.",
  "Caution: breathing may be hazardous to your health.",
  "Caution: Keep out of reach of children.",
  "Celebrate Hannibal Day this year.  Take an elephant to lunch.",
  "Change your thoughts and you change your world.",
  "Cheer Up!  Things are getting worse at a slower rate.",
  "Chess tonight.",
  "Chicken Little only has to be right once.",
  "Chicken Little was right.",
  "Cold hands, no gloves.",
  "Communicate!  It can't make things any worse.",
  "Courage is your greatest present need.",
  "Day of inquiry.  You will be subpoenaed.",
  "Do not overtax your powers.",
  "Do not sleep in a eucalyptus tree tonight.",
  "Do nothing unless you must, and when you must act -- hesitate.",
  "Do something unusual today.  Pay a bill.",
  "Do what comes naturally.  Seethe and fume and throw a tantrum.",
  "Domestic happiness and faithful friends.",
  "Don't feed the bats tonight.",
  "Don't get stuck in a closet -- wear yourself out.",
  "Don't get to bragging.",
  "Don't go surfing in South Dakota for a while.",
  "Don't hate yourself in the morning -- sleep till noon.",
  "Don't kiss an elephant on the lips today.",
  "Don't let your mind wander -- it's too little to be let out alone.",
  "Don't look back, the lemmings are gaining on you.",
  "Don't look now, but the man in the moon is laughing at you.",
  "Don't look now, but there is a multi-legged creature on your shoulder.",
  "Don't plan any hasty moves.  You'll be evicted soon anyway.",
  "Don't read any sky-writing for the next two weeks.",
  "Don't read everything you believe.",
  "Don't relax!  It's only your tension that's holding you together.",
  "Don't tell any big lies today.  Small ones can be just as effective.",
  "Don't worry so loud, your roommate can't think.",
  "Don't Worry, Be Happy.\n\t\t-- Meher Baba",
  "Don't worry.  Life's too long.\n\t\t-- Vincent Sardi, Jr.",
  "Don't you feel more like you do now than you did when you came in?",
  "Don't you wish you had more energy... or less ambition?",
  "Everything that you know is wrong, but you can be straightened out.",
  "Everything will be just tickety-boo today.",
  "Excellent day for putting Slinkies on an escalator.",
  "Excellent day to have a rotten day.",
  "Excellent time to become a missing person.",
  "Executive ability is prominent in your make-up.",
  "Exercise caution in your daily affairs.",
  "Expect a letter from a friend who will ask a favor of you.",
  "Expect the worst, it's the least you can do.",
  "Fine day for friends.\nSo-so day for you.",
  "Fine day to work off excess energy.  Steal something heavy.",
  "Fortune: You will be attacked next Wednesday at 3:15 p.m. by six samurai\nsword wielding purple fish glued to Harley-Davidson motorcycles.\n\nOh, and have a nice day!\n\t\t-- Bryce Nesbitt '84",
  "Future looks spotty.  You will spill soup in late evening.",
  "Generosity and perfection are your everlasting goals.",
  "Give him an evasive answer.",
  "Give thought to your reputation.  Consider changing name and moving to\na new town.",
  "Give your very best today.  Heaven knows it's little enough.",
  "Go to a movie tonight.  Darkness becomes you.",
  "Good day for a change of scene.  Repaper the bedroom wall.",
  "Good day for overcoming obstacles.  Try a steeplechase.",
  "Good day to deal with people in high places; particularly lonely stewardesses.",
  "Good day to let down old friends who need help.",
  "Good news from afar can bring you a welcome visitor.",
  "Good news.  Ten weeks from Friday will be a pretty good day.",
  "Good night to spend with family, but avoid arguments with your mate's\nnew lover.",
  "Green light in A.M. for new projects.  Red light in P.M. for traffic tickets.",
  "Hope that the day after you die is a nice day.",
  "If you can read this, you're too close.",
  "If you learn one useless thing every day, in a single year you'll learn\n365 useless things.",
  "If you sow your wild oats, hope for a crop failure.",
  "If you stand on your head, you will get footprints in your hair.",
  "If you think last Tuesday was a drag, wait till you see what happens tomorrow!",
  "If your life was a horse, you'd have to shoot it.",
  "In the stairway of life, you'd best take the elevator.",
  "Increased knowledge will help you now.  Have mate's phone bugged.",
  "Is that really YOU that is reading this?",
  "Is this really happening?",
  "It is so very hard to be an\non-your-own-take-care-of-yourself-because-there-is-no-one-else-to-do-it-for-you\ngrown-up.",
  "It may or may not be worthwhile, but it still has to be done.",
  "It was all so different before everything changed.",
  "It's a very *UN*lucky week in which to be took dead.\n\t\t-- Churchy La Femme",
  "It's all in the mind, ya know.",
  "It's lucky you're going so slowly, because you're going in the wrong direction.",
  "Just because the message may never be received does not mean it is\nnot worth sending.",
  "Just to have it is enough.",
  "Keep emotionally active.  Cater to your favorite neurosis.",
  "Keep it short for pithy sake.",
  "Lady Luck brings added income today.  Lady friend takes it away tonight.",
  "Learn to pause -- or nothing worthwhile can catch up to you.",
  "Let me put it this way: today is going to be a learning experience.",
  "Life is to you a dashing and bold adventure.",
  "\"Life, loathe it or ignore it, you can't like it.\"\n\t\t-- Marvin, \"Hitchhiker's Guide to the Galaxy\"",
  "Live in a world of your own, but always welcome visitors.",
  "Living your life is a task so difficult, it has never been attempted before.",
  "Long life is in store for you.",
  "Look afar and see the end from the beginning.",
  "Love is in the offing.  Be affectionate to one who adores you.",
  "Make a wish, it might come true.",
  "Many changes of mind and mood; do not hesitate too long.",
  "Never be led astray onto the path of virtue.",
  "Never commit yourself!  Let someone else commit you.",
  "Never give an inch!",
  "Never look up when dragons fly overhead.",
  "Never reveal your best argument.",
  "Next Friday will not be your lucky day.  As a matter of fact, you don't\nhave a lucky day this year.",
  "Of course you have a purpose -- to find a purpose.",
  "People are beginning to notice you.  Try dressing before you leave the house.",
  "Perfect day for scrubbing the floor and other exciting things.",
  "Questionable day.\n\nAsk somebody something.",
  "Reply hazy, ask again later.",
  "Save energy: be apathetic.",
  "Ships are safe in harbor, but they were never meant to stay there.",
  "Slow day.  Practice crawling.",
  "Snow Day -- stay home.",
  "So this is it.  We're going to die.",
  "So you're back... about time...",
  "Someone is speaking well of you.",
  "Someone is speaking well of you.\n\nHow unusual!",
  "Someone whom you reject today, will reject you tomorrow.",
  "Stay away from flying saucers today.",
  "Stay away from hurricanes for a while.",
  "Stay the curse.",
  "That secret you've been guarding, isn't.",
  "The time is right to make new friends.",
  "The whole world is a tuxedo and you are a pair of brown shoes.\n\t\t-- George Gobel",
  "There is a 20% chance of tomorrow.",
  "There is a fly on your nose.",
  "There was a phone call for you.",
  "There will be big changes for you but you will be happy.",
  "Things will be bright in P.M.  A cop will shine a light in your face.",
  "Think twice before speaking, but don't say \"think think click click\".",
  "This life is yours.  Some of it was given to you; the rest, you made yourself.",
  "This will be a memorable month -- no matter how hard you try to forget it.",
  "Time to be aggressive.  Go after a tattooed Virgo.",
  "Today is National Existential Ennui Awareness Day.",
  "Today is the first day of the rest of the mess.",
  "Today is the first day of the rest of your life.",
  "Today is the last day of your life so far.",
  "Today is the tomorrow you worried about yesterday.",
  "Today is what happened to yesterday.",
  "Today's weirdness is tomorrow's reason why.\n\t\t-- Hunter S. Thompson",
  "Tomorrow will be cancelled due to lack of interest.",
  "Tomorrow, this will be part of the unchangeable past but fortunately,\nit can still be changed today.",
  "Tomorrow, you can be anywhere.",
  "Tonight you will pay the wages of sin; Don't forget to leave a tip.",
  "Tonight's the night: Sleep in a eucalyptus tree.",
  "Troubled day for virgins over 16 who are beautiful and wealthy and live\nin eucalyptus trees.",
  "Truth will out this morning.  (Which may really mess things up.)",
  "Try the Moo Shu Pork.  It is especially good today.",
  "Try to get all of your posthumous medals in advance.",
  "Try to have as good a life as you can under the circumstances.",
  "Try to relax and enjoy the crisis.\n\t\t-- Ashleigh Brilliant",
  "Try to value useful qualities in one who loves you.",
  "Tuesday After Lunch is the cosmic time of the week.",
  "Tuesday is the Wednesday of the rest of your life.",
  "What happened last night can happen again.",
  "While you recently had your problems on the run, they've regrouped and\nare making another attack.",
  "Write yourself a threatening letter and pen a defiant reply.",
  "You are a bundle of energy, always on the go.",
  "You are a fluke of the universe; you have no right to be here.",
  "You are a very redundant person, that's what kind of person you are.",
  "You are always busy.",
  "You are as I am with You.",
  "You are capable of planning your future.",
  "You are confused; but this is your normal state.",
  "You are deeply attached to your friends and acquaintances.",
  "You are destined to become the commandant of the fighting men of the\ndepartment of transportation.",
  "You are dishonest, but never to the point of hurting a friend.",
  "You are fairminded, just and loving.",
  "You are farsighted, a good planner, an ardent lover, and a faithful friend.",
  "You are fighting for survival in your own sweet and gentle way.",
  "You are going to have a new love affair.",
  "You are magnetic in your bearing.",
  "You are not dead yet.  But watch for further reports.",
  "You are number 6!  Who is number one?",
  "You are only young once, but you can stay immature indefinitely.",
  "You are scrupulously honest, frank, and straightforward.  Therefore you\nhave few friends.",
  "You are sick, twisted and perverted.  I like that in a person.",
  "You are so boring that when I see you my feet go to sleep.",
  "You are standing on my toes.",
  "You are taking yourself far too seriously.",
  "You are the only person to ever get this message.",
  "You are wise, witty, and wonderful, but you spend too much time reading\nthis sort of trash.",
  "You attempt things that you do not even plan because of your extreme stupidity.",
  "You can create your own opportunities this week.  Blackmail a senior executive.",
  "You can do very well in speculation where land or anything to do with dirt\nis concerned.",
  "You can rent this space for only $5 a week.",
  "You could live a better life, if you had a better mind and a better body.",
  "You definitely intend to start living sometime soon.",
  "You dialed 5483.",
  "You display the wonderful traits of charm and courtesy.",
  "You don't become a failure until you're satisfied with being one.",
  "You enjoy the company of other people.",
  "You feel a whole lot more like you do now than you did when you used to.",
  "You fill a much-needed gap.",
  "You get along very well with everyone except animals and people.",
  "You had some happiness once, but your parents moved away, and you had to\nleave it behind.",
  "You have a deep appreciation of the arts and music.",
  "You have a deep interest in all that is artistic.",
  "You have a reputation for being thoroughly reliable and trustworthy.\nA pity that it's totally undeserved.",
  "You have a strong appeal for members of the opposite sex.",
  "You have a strong appeal for members of your own sex.",
  "You have a strong desire for a home and your family interests come first.",
  "You have a truly strong individuality.",
  "You have a will that can be influenced by all with whom you come in contact.",
  "You have an ability to sense and know higher truth.",
  "You have an ambitious nature and may make a name for yourself.",
  "You have an unusual equipment for success.  Be sure to use it properly.",
  "You have an unusual magnetic personality.  Don't walk too close to\nmetal objects which are not fastened down.",
  "You have an unusual understanding of the problems of human relationships.",
  "You have been selected for a secret mission.",
  "You have Egyptian flu: you're going to be a mummy.",
  "You have had a long-term stimulation relative to business.",
  "You have literary talent that you should take pains to develop.",
  "You have many friends and very few living enemies.",
  "You have no real enemies.",
  "You have taken yourself too seriously.",
  "You have the body of a 19 year old.  Please return it before it gets wrinkled.",
  "You have the capacity to learn from mistakes.  You'll learn a lot today.",
  "You have the power to influence all with whom you come in contact.",
  "You learn to write as if to someone else because NEXT YEAR YOU WILL BE\n\"SOMEONE ELSE.\"",
  "You like to form new friendships and make new acquaintances.",
  "You look like a million dollars.  All green and wrinkled.",
  "You look tired.",
  "You love peace.",
  "You love your home and want it to be beautiful.",
  "You may be gone tomorrow, but that doesn't mean that you weren't here today.",
  "You may be infinitely smaller than some things, but you're infinitely\nlarger than others.",
  "You may be recognized soon.  Hide.",
  "You may get an opportunity for advancement today.  Watch it!",
  "You may worry about your hair-do today, but tomorrow much peanut butter will\nbe sold.",
  "You need more time; and you probably always will.",
  "You need no longer worry about the future.  This time tomorrow you'll be dead.",
  "You never hesitate to tackle the most difficult problems.",
  "You never know how many friends you have until you rent a house on the beach.",
  "You now have Asian Flu.",
  "You own a dog, but you can only feed a cat.",
  "You plan things that you do not even attempt because of your extreme caution.",
  "You possess a mind not merely twisted, but actually sprained.",
  "You prefer the company of the opposite sex, but are well liked by your own.",
  "You recoil from the crude; you tend naturally toward the exquisite.",
  "You seek to shield those you love and you like the role of the provider.",
  "You shall be rewarded for a dastardly deed.",
  "You should emulate your heroes, but don't carry it too far.  Especially\nif they are dead.",
  "You should go home.",
  "You single-handedly fought your way into this hopeless mess.",
  "You teach best what you most need to learn.",
  "You too can wear a nose mitten.",
  "You two ought to be more careful--your love could drag on for years and years.",
  "You will always get the greatest recognition for the job you least like.",
  "You will always have good luck in your personal affairs.",
  "You will attract cultured and artistic people to your home.",
  "You will be a winner today.  Pick a fight with a four-year-old.",
  "You will be advanced socially, without any special effort on your part.",
  "You will be aided greatly by a person whom you thought to be unimportant.",
  "You will be attacked by a beast who has the body of a wolf, the tail of\na lion, and the face of Donald Duck.",
  "You will be audited by the Internal Revenue Service.",
  "You will be awarded a medal for disregarding safety in saving someone.",
  "You will be awarded some great honor.",
  "You will be awarded the Nobel Peace Prize... posthumously.",
  "You will be called upon to help a friend in trouble.",
  "You will be divorced within a year.",
  "You will be given a post of trust and responsibility.",
  "You will be held hostage by a radical group.",
  "You will be honored for contributing your time and skill to a worthy cause.",
  "You will be imprisoned for contributing your time and skill to a bank robbery.",
  "You will be married within a year, and divorced within two.",
  "You will be married within a year.",
  "You will be misunderstood by everyone.",
  "You will be recognized and honored as a community leader.",
  "You will be reincarnated as a toad; and you will be much happier.",
  "You will be run over by a beer truck.",
  "You will be run over by a bus.",
  "You will be singled out for promotion in your work.",
  "You will be successful in love.",
  "You will be surprised by a loud noise.",
  "You will be surrounded by luxury.",
  "You will be the last person to buy a Chrysler.",
  "You will be the victim of a bizarre joke.",
  "You will be Told about it Tomorrow.  Go Home and Prepare Thyself.",
  "You will be traveling and coming into a fortune.",
  "You will be winged by an anti-aircraft battery.",
  "You will become rich and famous unless you don't.",
  "You will contract a rare disease.",
  "You will engage in a profitable business activity.",
  "You will experience a strong urge to do good; but it will pass.",
  "You will feel hungry again in another hour.",
  "You will forget that you ever knew me.",
  "You will gain money by a fattening action.",
  "You will gain money by a speculation or lottery.",
  "You will gain money by an illegal action.",
  "You will gain money by an immoral action.",
  "You will get what you deserve.",
  "You will give someone a piece of your mind, which you can ill afford.",
  "You will have a long and boring life.",
  "You will have a long and unpleasant discussion with your supervisor.",
  "You will have domestic happiness and faithful friends.",
  "You will have good luck and overcome many hardships.",
  "You will have long and healthy life.",
  "You will hear good news from one you thought unfriendly to you.",
  "You will inherit millions of dollars.",
  "You will inherit some money or a small piece of land.",
  "You will live a long, healthy, happy life and make bags of money.",
  "You will live to see your grandchildren.",
  "You will lose your present job and have to become a door to door mayonnaise\nsalesman.",
  "You will meet an important person who will help you advance professionally.",
  "You will never know hunger.",
  "You will not be elected to public office this year.",
  "You will obey or molten silver will be poured into your ears.",
  "You will outgrow your usefulness.",
  "You will overcome the attacks of jealous associates.",
  "You will pass away very quickly.",
  "You will pay for your sins.  If you have already paid, please disregard\nthis message.",
  "You will pioneer the first Martian colony.",
  "You will probably marry after a very brief courtship.",
  "You will reach the highest possible point in your business or profession.",
  "You will receive a legacy which will place you above want.",
  "You will remember something that you should not have forgotten.",
  "You will soon forget this.",
  "You will soon meet a person who will play an important role in your life.",
  "You will step on the night soil of many countries.",
  "You will stop at nothing to reach your objective, but only because your\nbrakes are defective.",
  "You will triumph over your enemy.",
  "You will visit the Dung Pits of Glive soon.",
  "You will win success in whatever calling you adopt.",
  "You will wish you hadn't.",
  "You work very hard.  Don't try to think as well.",
  "You worry too much about your job.  Stop it.  You are not paid enough to worry.",
  "You would if you could but you can't so you won't.",
  "You'd like to do it instantaneously, but that's too slow.",
  "You'll be called to a post requiring ability in handling groups of people.",
  "You'll be sorry...",
  "You'll feel devilish tonight.  Toss dynamite caps under a flamenco dancer's\nheel.",
  "You'll feel much better once you've given up hope.",
  "You'll never be the man your mother was!",
  "You'll never see all the places, or read all the books, but fortunately,\nthey're not all recommended.",
  "You'll wish that you had done some of the hard things when they were easier\nto do.",
  "You're a card which will have to be dealt with.",
  "You're almost as happy as you think you are.",
  "You're at the end of the road again.",
  "You're being followed.  Cut out the hanky-panky for a few days.",
  "You're currently going through a difficult transition period called \"Life.\"",
  "You're definitely on their list.  The question to ask next is what list it is.",
  "You're growing out of some of your problems, but there are others that\nyou're growing into.",
  "You're not my type.  For that matter, you're not even my species!!!",
  "You're ugly and your mother dresses you funny.",
  "You're working under a slight handicap.  You happen to be human.",
  "You've been leading a dog's life.  Stay off the furniture.",
  "Your aim is high and to the right.",
  "Your aims are high, and you are capable of much.",
  "Your analyst has you mixed up with another patient.  Don't believe a\nthing he tells you.",
  "Your best consolation is the hope that the things you failed to get weren't\nreally worth having.",
  "Your boss climbed the corporate ladder, wrong by wrong.",
  "Your boss is a few sandwiches short of a picnic.",
  "Your boyfriend takes chocolate from strangers.",
  "Your business will assume vast proportions.",
  "Your business will go through a period of considerable expansion.",
  "Your depth of comprehension may tend to make you lax in worldly ways.",
  "Your domestic life may be harmonious.",
  "Your fly might be open (but don't check it just now).",
  "Your goose is cooked.\n(Your current chick is burned up too!)",
  "Your heart is pure, and your mind clear, and your soul devout.",
  "Your ignorance cramps my conversation.",
  "Your life would be very empty if you had nothing to regret.",
  "Your love life will be happy and harmonious.",
  "Your love life will be... interesting.",
  "Your lover will never wish to leave you.",
  "Your lucky color has faded.",
  "Your lucky number has been disconnected.",
  "Your lucky number is 3552664958674928.  Watch for it everywhere.",
  "Your mode of life will be changed for the better because of good news soon.",
  "Your mode of life will be changed for the better because of new developments.",
  "Your motives for doing whatever good deed you may have in mind will be\nmisinterpreted by somebody.",
  "Your nature demands love and your happiness depends on it.",
  "Your object is to save the world, while still leading a pleasant life.",
  "Your own qualities will help prevent your advancement in the world.",
  "Your present plans will be successful.",
  "Your reasoning is excellent -- it's only your basic assumptions that are wrong.",
  "Your reasoning powers are good, and you are a fairly good planner.",
  "Your sister swims out to meet troop ships.",
  "Your society will be sought by people of taste and refinement.",
  "Your step will soil many countries.",
  "Your supervisor is thinking about you.",
  "Your talents will be recognized and suitably rewarded.",
  "Your temporary financial embarrassment will be relieved in a surprising manner.",
  "Your true value depends entirely on what you are compared with.",
  "\"How do you pronounce SunOS?\"  \"Just like you hear it, with a big SOS\"\n\t\t-- dedicated to Roland Kaltefleiter",
  "finlandia:~> apropos win\nwin: nothing appropriate.",
  "C:\\> WIN\nBad command or filename\n\nC:\\> LOSE\nLoading Microsoft Windows ...",
  "Linux ext2fs has been stable for a long time, now it's time to break it\n\t-- Linux-Kongress '95 in Berlin",
  "The state of some commercial Un*x is more unsecure than any Linux box\nwithout a root password...\n\t-- Bernd Eckenfels",
  "Less is more or less more\n\t-- Y_Plentyn on #LinuxGER",
  "Let's call it an accidental feature.\n\t--Larry Wall",
  ".........    Escape the 'Gates' of Hell\n  `:::'                  .......  ......\n   :::  *                  `::.    ::'\n   ::: .::  .:.::.  .:: .::  `::. :'\n   :::  ::   ::  ::  ::  ::    :::.\n   ::: .::. .::  ::.  `::::. .:'  ::.\n...:::.....................::'   .::::..\n\t-- William E. Roadcap",
  "Win95 is not a virus; a virus does something.\n\t-- unknown source",
  "Machine Always Crashes, If Not, The Operating System Hangs (MACINTOSH)\n\t-- Topic on #Linux",
  "Except for Great Britain. According to ISO 9166 and Internet reality\nGreat Britain's toplevel domain should be _gb_.  Instead, Great Britain\nand Nortern Ireland (the United Kingdom) use the toplevel domain _uk_.\nThey drive on the wrong side of the road, too.\n\t-- PERL book (or DNS and BIND book)",
  "Save yourself from the 'Gates' of hell, use Linux.\"  -- like that one.\n\t-- The_Kind @ LinuxNet",
  "I did this 'cause Linux gives me a woody.  It doesn't generate revenue.\n\t-- Dave '-ddt->` Taylor, announcing DOOM for Linux",
  "Feel free to contact me (flames about my english and the useless of this\ndriver will be redirected to /dev/null, oh no, it's full...).\n\t-- Michael Beck, describing the PC-speaker sound device",
  "    if (argc > 1 && strcmp(argv[1], \"-advice\") == 0) {\n\tprintf(\"Don't Panic!\\n\");\n\texit(42);\n    }\n\n\t-- Arnold Robbins in the LJ of February '95, describing RCS",
  "lp1 on fire\n\t-- One of the more obfuscated kernel messages",
  "A Linux machine!  Because a 486 is a terrible thing to waste!\n\t-- Joe Sloan, jjs@wintermute.ucr.edu",
  "Microsoft is not the answer.\nMicrosoft is the question.\nNO (or Linux) is the answer.\n\t-- Taken from a .signature from someone from the UK, source unknown",
  "In most countries selling harmful things like drugs is punishable.\nThen how come people can sell Microsoft software and go unpunished?\n\t-- Hasse Skrifvars, hasku@rost.abo.fi,",
  "Fatal Error: Found [MS-Windows] System -> Repartitioning Disk for Linux...\n(By cbbrown@io.org, Christopher Browne)",
  "Windows without the X is like making love without a partner.\n\t-- MaDsen Wikholm, mwikholm@at8.abo.fi",
  "Sex, Drugs & Linux Rules\n\t-- MaDsen Wikholm, mwikholm@at8.abo.fi",
  "win-nt from the people who invented edlin.\n\t-- MaDsen Wikholm, mwikholm@at8.abo.fi",
  "Apples  have  meant  trouble  since  eden.\n\t-- MaDsen Wikholm, mwikholm@at8.abo.fi",
  "Linux, the way to get rid of boot viruses\n\t-- MaDsen Wikholm, mwikholm@at8.abo.fi",
  "This  message was brought to  you by Linux, the free  unix.\nWindows without the X is like making love without a partner.\nSex, Drugs & Linux Rules\nwin-nt from the people who invented edlin\napples  have  meant  trouble  since  eden\nLinux, the way to get rid of boot viruses\n\n\t-- MaDsen Wikholm, mwikholm@at8.abo.fi",
  "Once upon a time there was a DOS user who saw Unix, and saw that it was\ngood.  After typing cp on his DOS machine at home, he downloaded GNU's\nunix tools ported to DOS and installed them.  He rm'd, cp'd, and mv'd\nhappily for many days, and upon finding elvis, he vi'd and was happy.  After\na long day at work (on a Unix box) he came home, started editing a file,\nand couldn't figure out why he couldn't suspend vi (w/ ctrl-z) to do\na compile.\n\t\t-- Erik Troan, ewt@tipper.oit.unc.edu",
  "We are MicroSoft.  You will be assimilated.  Resistance is futile.\n\t\t-- Attributed to B.G., Gill Bates",
  "Avoid the Gates of Hell.  Use Linux\n\t\t-- Unknown source",
  "Intel engineering seem to have misheard Intel marketing strategy.  The\nphrase was \"Divide and conquer\" not \"Divide and cock up\"\n\t\t-- Alan Cox, iialan@www.linux.org.uk",
  "Linux!  Guerrilla UNIX Development     Venimus, Vidimus, Dolavimus.\n\t\t-- Mark A. Horton KA4YBR, mah@ka4ybr.com",
  "----==-- _                     / /  \\\n---==---(_)__  __ ____  __    / / /\\ \\\n--==---/ / _ \\/ // /\\ \\/ /   / /_/\\ \\ \\\n-=====/_/_//_/\\_,_/ /_/\\_\\  /______\\ \\ \\\nA proud member of TeamLinux \\_________\\/\n\t\t-- CHaley (HAC), haley@unm.edu, ch008cth@pi.lanl.gov)",
  "\"Who is General Failure and why is he reading my hard disk?\"\nMicrosoft spel chekar vor sail, worgs grate !!\n\t\t-- Felix von Leitner, leitner@inf.fu-berlin.de",
  "Personally, I think my choice in the mostest-superlative-computer wars has to\nbe the HP-48 series of calculators.  They'll run almost anything.  And if they\ncan't, while I'll just plug a Linux box into the serial port and load up the\nHP-48 VT-100 emulator.\n\t\t-- Jeff Dege, jdege@winternet.com",
  "/*\n * Oops. The kernel tried to access some bad page. We'll have to\n * terminate things with extreme prejudice.\n*/\ndie_if_kernel(\"Oops\", regs, error_code);\n\t\t-- From linux/arch/i386/mm/fault.c",
  "Linux: because a PC is a terrible thing to waste\n\t\t-- ksh@cis.ufl.edu put this on Tshirts in '93",
  "Linux: the choice of a GNU generation\n\t\t-- ksh@cis.ufl.edu put this on Tshirts in '93",
  "There are two types of Linux developers - those who can spell, and\nthose who can't.  There is a constant pitched battle between the two.\n\t\t-- From one of the post-1.1.54 kernel update messages posted to c.o.l.a",
  "> > Other than the fact Linux has a cool name, could someone explain why I\n> > should use Linux over BSD?\n>\n> No.  That's it.  The cool name, that is.  We worked very hard on\n> creating a name that would appeal to the majority of people, and it\n> certainly paid off: thousands of people are using linux just to be able\n> to say \"OS/2? Hah.  I've got Linux.  What a cool name\".  386BSD made the\n> mistake of putting a lot of numbers and weird abbreviations into the\n> name, and is scaring away a lot of people just because it sounds too\n> technical.\n\t\t-- Linus Torvalds' follow-up to a question about Linux",
  "> The day people think linux would be better served by somebody else (FSF\n> being the natural alternative), I'll \"abdicate\".  I don't think that\n> it's something people have to worry about right now - I don't see it\n> happening in the near future.  I enjoy doing linux, even though it does\n> mean some work, and I haven't gotten any complaints (some almost timid\n> reminders about a patch I have forgotten or ignored, but nothing\n> negative so far).\n>\n> Don't take the above to mean that I'll stop the day somebody complains:\n> I'm thick-skinned (Lasu, who is reading this over my shoulder commented\n> that \"thick-HEADED is closer to the truth\") enough to take some abuse.\n> If I weren't, I'd have stopped developing linux the day ast ridiculed me\n> on c.o.minix.  What I mean is just that while linux has been my baby so\n> far, I don't want to stand in the way if people want to make something\n> better of it (*).\n>\n>                 Linus\n>\n> (*) Hey, maybe I could apply for a saint-hood from the Pope.  Does\n> somebody know what his email-address is? I'm so nice it makes you puke.\n\t\t-- Taken from Linus's reply to someone worried about the future of Linux",
  "> : Any porters out there should feel happier knowing that DEC is shipping\n> : me an AlphaPC that I intend to try getting linux running on: this will\n> : definitely help flush out some of the most flagrant unportable stuff.\n> : The Alpha is much more different from the i386 than the 68k stuff is, so\n> : it's likely to get most of the stuff fixed.\n>\n> It's posts like this that almost convince us non-believers that there\n> really is a god.\n\t-- Anthony Lovell, to Linus's remarks about porting",
  "When you say \"I wrote a program that crashed Windows\", people just stare at\nyou blankly and say \"Hey, I got those with the system, *for free*\".\n\t-- Linus Torvalds",
  "We come to bury DOS, not to praise it.\n\t-- Paul Vojta, vojta@math.berkeley.edu\n    ( paraphrasing a quote of Shakespeare)",
  "Be warned that typing \\fBkillall \\fIname\\fP may not have the desired\neffect on non-Linux systems, especially when done by a privileged user.\n\t-- From the killall manual page",
  "Note that if I can get you to \"su and say\" something just by asking,\nyou have a very serious security problem on your system and you should\nlook into it.\n\t-- Paul Vixie, vixie-cron 3.0.1 installation notes",
  "How should I know if it works?  That's what beta testers are for.  I\nonly coded it.\n\n\t-- Attributed to Linus Torvalds, somewhere in a posting",
  "I develop for Linux for a living, I used to develop for DOS.\nGoing from DOS to Linux is like trading a glider for an F117.\n\t-- Lawrence Foard, entropy@world.std.com",
  "Absolutely nothing should be concluded from these figures except that\nno conclusion can be drawn from them.\n\t-- Joseph L. Brothers, Linux/PowerPC Project)",
  "If the future navigation system [for interactive networked services on\nthe NII] looks like something from Microsoft, it will never work.\n\t-- Chairman of Walt Disney Television & Telecommunications",
  "Problem solving under Linux has never been the circus that it is under\nAIX.\n\t-- Pete Ehlke in comp.unix.aix",
  "I don't know why, but first C programs tend to look a lot worse than\nfirst programs in any other language (maybe except for fortran, but then\nI suspect all fortran programs look like `firsts')\n\t-- Olaf Kirch",
  "On a normal ascii line, the only safe condition to detect is a 'BREAK'\n- everything else having been assigned functions by Gnu EMACS.\n\t-- Tarl Neustaedter",
  "By golly, I'm beginning to think Linux really *is* the best thing since\nsliced bread.\n\t-- Vance Petree, Virginia Power",
  "I'd crawl over an acre of 'Visual This++' and 'Integrated Development\nThat' to get to gcc, Emacs, and gdb.  Thank you.\n\t-- Vance Petree, Virginia Power",
  "Oh, I've seen copies [of Linux Journal] around the terminal room at The Labs.\n\t-- Dennis Ritchie",
  "If you want to travel around the world and be invited to speak at a lot\nof different places, just write a Unix operating system.\n\t-- Linus Torvalds",
  "...and scantily clad females, of course.  Who cares if it's below zero\noutside.\n\t-- Linus Torvalds",
  "...you might as well skip the Xmas celebration completely, and instead\nsit in front of your linux computer playing with the all-new-and-improved\nlinux kernel version.\n\t-- Linus Torvalds",
  "Besides, I think Slackware sounds better than 'Microsoft,' don't you?\n\t-- Patrick Volkerding",
  "All language designers are arrogant. Goes with the territory...\n\t-- Larry Wall",
  "And the next time you consider complaining that running Lucid Emacs\n19.05 via NFS from a remote Linux machine in Paraguay doesn't seem to\nget the background colors right, you'll know who to thank.\n\t-- Matt Welsh",
  "Are Linux users lemmings collectively jumping off of the cliff of\nreliable, well-engineered commercial software?\n\t-- Matt Welsh",
  "Even more amazing was the realization that God has Internet access.  I\nwonder if He has a full newsfeed?\n\t-- Matt Welsh",
  "I once witnessed a long-winded, month-long flamewar over the use of\nmice vs. trackballs... It was very silly.\n\t-- Matt Welsh",
  "Linux poses a real challenge for those with a taste for late-night\nhacking (and/or conversations with God).\n\t-- Matt Welsh",
  "What you end up with, after running an operating system concept through\nthese many marketing coffee filters, is something not unlike plain hot\nwater.\n\t-- Matt Welsh",
  "...Deep Hack Mode -- that mysterious and frightening state of\nconsciousness where Mortal Users fear to tread.\n\t-- Matt Welsh",
  "...Unix, MS-DOS, and Windows NT (also known as the Good, the Bad, and\nthe Ugly).\n\t-- Matt Welsh",
  "...very few phenomena can pull someone out of Deep Hack Mode, with two\nnoted exceptions: being struck by lightning, or worse, your *computer*\nbeing struck by lightning.\n\t-- Matt Welsh",
  "..you could spend *all day* customizing the title bar.  Believe me.  I\nspeak from experience.\n\t-- Matt Welsh",
  "[In 'Doctor' mode], I spent a good ten minutes telling Emacs what I\nthought of it.  (The response was, 'Perhaps you could try to be less\nabusive.')\n\t-- Matt Welsh",
  "I would rather spend 10 hours reading someone else's source code than\n10 minutes listening to Musak waiting for technical support which isn't.\n\t-- Dr. Greg Wettstein, Roger Maris Cancer Center",
  "...[Linux's] capacity to talk via any medium except smoke signals.\n\t-- Dr. Greg Wettstein, Roger Maris Cancer Center",
  "Whip me.  Beat me.  Make me maintain AIX.\n\t-- Stephan Zielinski",
  "Your job is being a professor and researcher: That's one hell of a good excuse\nfor some of the brain-damages of minix.\n\t-- Linus Torvalds to Andrew Tanenbaum",
  "I still maintain the point that designing a monolithic kernel in 1991 is a\nfundamental error.  Be thankful you are not my student.  You would not get a\nhigh grade for such a design :-)\n\t-- Andrew Tanenbaum to Linus Torvalds",
  "We use Linux for all our mission-critical applications.  Having the source code\nmeans that we are not held hostage by anyone's support department.\n\t-- Russell Nelson, President of Crynwr Software",
  "Linux is obsolete\n\t-- Andrew Tanenbaum",
  "Dijkstra probably hates me.\n\t-- Linus Torvalds, in kernel/sched.c",
  "And 1.1.81 is officially BugFree(tm), so if you receive any bug-reports\non it, you know they are just evil lies.\n\t-- Linus Torvalds",
  "We are Pentium of Borg.  Division is futile.  You will be approximated.\n\t-- seen in someone's .signature",
  "Linux: the operating system with a CLUE... Command Line User Environment.\n\t-- seen in a posting in comp.software.testing",
  "quit   When the quit statement is read, the  bc  processor\n       is  terminated, regardless of where the quit state-\n       ment is found.  For example, \"if  (0  ==  1)  quit\"\n       will cause bc to terminate.\n\t-- seen in the manpage for \"bc\". Note the \"if\" statement's logic",
  "Sic transit discus mundi\n\t-- From the System Administrator's Guide, by Lars Wirzenius",
  "Sigh.  I like to think it's just the Linux people who want to be on\nthe \"leading edge\" so bad they walk right off the precipice.\n\t-- Craig E. Groeschel",
  "We all know Linux is great... it does infinite loops in 5 seconds.\n\t- Linus Torvalds about the superiority of Linux on the Amsterdam Linux\n    Symposium",
  "Waving away a cloud of smoke, I look up, and am blinded by a bright, white\nlight.  It's God. No, not Richard Stallman, or Linus Torvalds, but God. In\na booming voice, He says: \"THIS IS A SIGN. USE LINUX, THE FREE UNIX SYSTEM\nFOR THE 386.\n\t-- Matt Welsh",
  "The chat program is in public domain.  This is not the GNU public license.\nIf it breaks then you get to keep both pieces.\n\t-- Copyright notice for the chat program",
  "'Mounten' wird für drei Dinge benutzt: 'Aufsitzen' auf Pferde, 'einklinken'\nvon Festplatten in Dateisysteme, und, nun, 'besteigen' beim Sex.\n\n'Mounting' is used for three things: climbing on a horse, linking in a\nhard disk unit in data systems, and, well, mounting during sex.\n\n\t-- Christa Keil",
  "Manchmal stehe nachts auf und installier's mir einfach...\n\t-- H0arry @ IRC",
  "We are using Linux daily to UP our productivity - so UP yours!\n\t-- Adapted from Pat Paulsen by Joe Sloan",
  "But what can you do with it?\n\t-- ubiquitous cry from Linux-user partner\n    -- (Submitted by Andy Pearce, ajp@hpopd.pwd.hp.com)",
  "/*\n * [...] Note that 120 sec is defined in the protocol as the maximum\n * possible RTT.  I guess we'll have to use something other than TCP\n * to talk to the University of Mars.\n * PAWS allows us longer timeouts and large windows, so once implemented\n * ftp to mars will work nicely.\n */\n\t-- from /usr/src/linux/net/inet/tcp.c, concerning RTT [round trip time]",
  "DOS: n., A small annoying boot virus that causes random spontaneous system\n     crashes, usually just before saving a massive project.  Easily cured by\n     UNIX.  See also MS-DOS, IBM-DOS, DR-DOS.\n\t-- David Vicker's .plan",
  "MSDOS didn't get as bad as it is overnight -- it took over ten years\nof careful development.\n\t-- dmeggins@aix1.uottawa.ca",
  "LILO, you've got me on my knees!\n\t-- David Black, dblack@pilot.njin.net, with apologies to Derek and the\n       Dominos, and Werner Almsberger",
  "I've run DOOM more in the last few days than I have the last few\nmonths.  I just love debugging ;-)\n\t-- Linus Torvalds",
  "Microsoft Corp., concerned by the growing popularity of the free 32-bit\noperating system for Intel systems, Linux, has employed a number of top\nprogrammers from the underground world of virus development.  Bill Gates stated\nyesterday: \"World domination, fast -- it's either us or Linus\".  Mr. Torvalds\nwas unavailable for comment ...\n\t-- Robert Manners, rjm@swift.eng.ox.ac.uk, in comp.os.linux.setup",
  "The only \"intuitive\" interface is the nipple.  After that, it's all learned.\n\t-- Bruce Ediger, bediger@teal.csn.org, on X interfaces in c.o.l.misc",
  "After watching my newly-retired dad spend two weeks learning how to make a new\nfolder, it became obvious that \"intuitive\" mostly means \"what the writer or\nspeaker of intuitive likes\".\n    -- Bruce Ediger, bediger@teal.csn.org, on X the intuitiveness of a Mac\n    interface on comp.os.linux.misc.",
  "Now I know someone out there is going to claim, \"Well then, UNIX is intuitive,\nbecause you only need to learn 5000 commands, and then everything else follows\nfrom that! Har har har!\"\n\t-- Andy Bates on \"intuitive interfaces\", slightly defending Macs",
  "> No manual is ever necessary.\nMay I politely interject here: BULLSHIT.  That's the biggest Apple lie of all!\n\t-- Discussion in comp.os.linux.misc on the intuitiveness of interfaces",
  "How do I type \"for i in *.dvi do xdvi $i done\" in a GUI?\n\t-- Discussion in comp.os.linux.misc on the intuitiveness of interfaces",
  ">Ever heard of .cshrc?\nThat's a city in Bosnia.  Right?\n\t-- Discussion in comp.os.linux.misc on the intuitiveness of commands",
  "Now, it we had this sort of thing:\n  yield -a     for yield to all traffic\n  yield -t     for yield to trucks\n  yield -f     for yield to people walking (yield foot)\n  yield -d t*  for yield on days starting with t\n\n...you'd have a lot of dead people at intersections, and traffic jams you\nwouldn't believe...\n\t\t-- Discussion on the intuitiveness of commands, comp.os.linux.misc",
  "Not me, guy.  I read the Bash man page each day like a Jehovah's Witness reads\nthe Bible.  No wait, the Bash man page IS the bible.  Excuse me...\n\t\t-- More on confusing aliases, taken from comp.os.linux.misc",
  "On the Internet, no one knows you're using Windows NT\n\t\t-- Submitted by Ramiro Estrugo, restrugo@fateware.com",
  "> I'm an idiot..  At least this [bug] took about 5 minutes to find..\nDisquieting ...\n\t\t-- Gonzalo Tornaria in response to Linus Torvalds's",
  "> I'm an idiot..  At least this [bug] took about 5 minutes to find..\nWe need to find some new terms to describe the rest of us mere mortals\nthen.\n\t\t-- Craig Schlenter in response to Linus Torvalds's",
  "> I'm an idiot..  At least this [bug] took about 5 minutes to find..\nSurely, Linus is talking about the kind of idiocy that others aspire to :-).\n\t\t-- Bruce Perens in response to Linus Torvalds's",
  "Never make any mistaeks.\n\t\t-- Anonymous, in a mail discussion about a kernel bug report",
  "+#if defined(__alpha__) && defined(CONFIG_PCI)\n+       /*\n+        * The meaning of life, the universe, and everything. Plus\n+        * this makes the year come out right.\n+        */\n+       year -= 42;\n+#endif\n\t-- From the patch for 1.3.2: (kernel/time.c), submitted by Marcus Meissner",
  "As usual, this being a 1.3.x release, I haven't even compiled this\nkernel yet.  So if it works, you should be doubly impressed.\n\t-- Linus Torvalds, announcing kernel 1.3.3 on LKML",
  "People disagree with me.  I just ignore them.\n\t-- Linus Torvalds, regarding the use of C++ for the Linux kernel",
  "It's now the GNU Emacs of all terminal emulators.\n    -- Linus Torvalds, regarding the fact that Linux started off as a terminal\n    emulator",
  "Audience: What will become of Linux when the Hurd is ready?\nEric Youngdale: Err... is Richard Stallman here?\n\t-- From the Linux conference in spring '95, Berlin",
  "Linux: The OS people choose without $200,000,000 of persuasion.\n\t-- Mike Coleman",
  "The memory management on the PowerPC can be used to frighten small children.\n\t-- Linus Torvalds",
  "... faster BogoMIPS calculations (yes, it now boots 2 seconds faster than\nit used to: we're considering changing the name from \"Linux\" to \"InstaBOOT\"\n\t-- Linus, in the announcement for 1.3.26",
  "... of course, this probably only happens for tcsh which uses wait4(),\nwhich is why I never saw it.  Serves people who use that abomination\nright 8^)\n\t-- Linus Torvalds, about a patch that fixes getrusage for 1.3.26",
  "It's a bird..\nIt's a plane..\nNo, it's KernelMan, faster than a speeding bullet, to your rescue.\nDoing new kernel versions in under 5 seconds flat..\n\t-- Linus, in the announcement for 1.3.27",
  "Eh, that's it, I guess.  No 300 million dollar unveiling event for this\nkernel, I'm afraid, but you're still supposed to think of this as the\n\"happening of the century\" (at least until the next kernel comes along).\n\t-- Linus, in the announcement for 1.3.27",
  "Oh, and this is another kernel in that great and venerable \"BugFree(tm)\"\nseries of kernels.  So be not afraid of bugs, but go out in the streets\nand deliver this message of joy to the masses.\n\t-- Linus, in the announcement for 1.3.27",
  "When you say 'I wrote a program that crashed Windows', people just stare at\nyou blankly and say 'Hey, I got those with the system, *for free*'.\n\t-- Linus Torvalds",
  "Never trust an operating system you don't have sources for. ;-)\n\t-- Unknown source",
  "> Linux is not user-friendly.\nIt _is_ user-friendly.  It is not ignorant-friendly and idiot-friendly.\n\t-- Seen somewhere on the net",
  "Keep me informed on the behaviour of this kernel..  As the \"BugFree(tm)\"\nseries didn't turn out too well, I'm starting a new series called the\n\"ItWorksForMe(tm)\" series, of which this new kernel is yet another\nshining example.\n\t-- Linus, in the announcement for 1.3.29",
  "Seriously, the way I did this was by using a special /sbin/loader binary\nwith debugging hooks that I made (\"dd\" is your friend: binary editors\nare for wimps).\n\t-- Linus Torvalds, in an article on a dnserver",
  "(I tried to get some documentation out of Digital on this, but as far as\nI can tell even _they_ don't have it ;-)\n\t-- Linus Torvalds, in an article on a dnserver",
  "Q: Why shouldn't I simply delete the stuff I never use, it's just taking up\n   space?\nA: This question is in the category of Famous Last Words..\n\t-- From the Frequently Unasked Questions",
  "Q: What's the big deal about rm, I have been deleting stuff for years?  And\n   never lost anything.. oops!\nA: ...\n\t-- From the Frequently Unasked Questions",
  "Linux is addictive, I'm hooked!\n\t-- MaDsen Wikholm's .sig",
  "panic(\"Foooooooood fight!\");\n\t-- In the kernel source aha1542.c, after detecting a bad segment list",
  "Convention organizer to Linus Torvalds: \"You might like to come with us\nto some licensed[1] place, and have some pizza.\"\n\nLinus: \"Oh, I did not know that you needed a license to eat pizza\".\n\n[1] Licensed - refers in Australia to a restaurant which has government\nlicence to sell liquor.\n\t-- Linus at a talk at the Melbourne University",
  "Footnotes are for things you believe don't really belong in LDP manuals,\nbut want to include anyway.\n\t-- Joel N. Weber II discussing the 'make' chapter of LPG",
  "Eh, that's it, I guess.  No 300 million dollar unveiling event for this\nkernel, I'm afraid, but you're still supposed to think of this as the\n\"happening of the century\" (at least until the next kernel comes along).\nOh, and this is another kernel in that great and venerable \"BugFree(tm)\"\nseries of kernels. So be not afraid of bugs, but go out in the streets\nand deliver this message of joy to the masses.\n\t-- Linus Torvalds, on releasing 1.3.27",
  "Ok, I'm just uploading the new version of the kernel, v1.3.33, also\nknown as \"the buggiest kernel ever\".\n\t-- Linus Torvalds",
  "Go not unto the Usenet for advice, for you will be told both yea and nay (and\nquite a few things that just have nothing at all to do with the question).\n\t-- seen in a .sig somewhere",
  "Those who don't understand Linux are doomed to reinvent it, poorly.\n\t-- unidentified source",
  "Look, I'm about to buy me a double barreled sawed off shotgun and show\nLinus what I think about backspace and delete not working.\n\t-- some anonymous .signature",
  "I forgot to mention an important fact in the 1.3.67 announcement. In order to\nget a fully working kernel, you have to follow the steps below:\n - Walk around your computer widdershins 3 times, chanting \"Linus is\n   overworked, and he makes lousy patches, but we love him anyway\". Get\n   your spuouse to do this too for extra effect.  Children are optional.\n - Apply the patch included in this mail\n - Call your system \"Super-67\", and don't forget to unapply the patch\n   before you later applying the official 1.3.68 patch.\n - reboot\n\t-- Linus Torvalds, announcing another kernel patch",
  "We apologize for the inconvenience, but we'd still like yout to test out\nthis kernel.\n\t-- Linus Torvalds, announcing another kernel patch",
  "The new Linux anthem will be \"He's an idiot, but he's ok\", as performed by\nMonthy Python.  You'd better start practicing.\n\t-- Linus Torvalds, announcing another kernel patch",
  "How do you power off this machine?\n    -- Linus, when upgrading linux.cs.helsinki.fi, and after using the machine\n    for several months",
  "Excusing bad programming is a shooting offence, no matter _what_ the\ncircumstances.\n\t-- Linus Torvalds, to the linux-kernel list",
  "Linus?  Whose that?\n\t-- clueless newbie on #Linux",
  "N: Phil Lewis\nE: beans@bucket.ualr.edu\nD: Promised to send money if I would put his name in the source tree.\nS: PO Box 371\nS: North Little Rock, Arkansas 72115\nS: US\n\t-- /usr/src/linux/CREDITS",
  "> You know you are \"there\" when you are known by your first name, and\n> are recognized.\n> Lemmie see, there is Madonna, and Linus, and ..... help me out here!\nBill ? ;-)\n\t-- From some postings on comp.os.linux.misc",
  "Whoa...I did a 'zcat /vmlinuz > /dev/audio' and I think I heard God...\n\t-- mikecd on #Linux",
  "Some people have told me they don't think a fat penguin really embodies the\ngrace of Linux, which just tells me they have never seen a angry penguin\ncharging at them in excess of 100mph.  They'd be a lot more careful about what\nthey say if they had.\n\t-- Linus Torvalds, announcing Linux v2.0",
  "MS-DOS, you can't live with it, you can live without it.\n\t-- from Lars Wirzenius' .sig",
  "> If you don't need X then little VT-100 terminals are available for real\n> cheap.  Should be able to find decent ones used for around $40 each.\n> For that price, they're a must for the kitchen, den, bathrooms, etc.. :)\nYou're right. Can you explain this to my wife?\n\t-- Seen on c.o.l.development.system, on the subject of extra terminals",
  ".. I used to get in more fights with SCO than I did my girlfriend, but\nnow, thanks to Linux, she has more than happily accepted her place back at\nnumber one antagonist in my life..\n\t-- Jason Stiefel, krypto@s30.nmex.com",
  "I mean, well, if it were not for Linux I might be roaming the streets looking\nfor drugs or prostitutes or something.  Hannu and Linus have my highest\nadmiration (apple polishing mode off).\n\t-- Phil Lewis, plewis@nyx.nyx.net",
  "> What does ELF stand for (in respect to Linux?)\nELF is the first rock group that Ronnie James Dio performed with back in\nthe early 1970's.  In contrast, a.out is a misspelling of the French word\nfor the month of August.  What the two have in common is beyond me, but\nLinux users seem to use the two words together.\n\t-- seen on c.o.l.misc",
  "\"Linux was made by foreign terrorists to take money from true US companies\nlike Microsoft.\" - Some AOL'er.\n\"To this end we dedicate ourselves...\" -Don\n\t-- From the sig of \"Don\", don@cs.byu.edu",
  "Shoot me again.\nJust proving that the quickest way to solve the problem is to post a\nwhine to the newsgroups: within moments the solution presents itself to\nme, and meanwhile my ass is hanging out on the Net... *sigh*...\n\t-- Dave Phillips, dlphilp@bright.net, about problem solving via news",
  "> Is there any hope for me? Am I just thick? Does anyone remember the\n> Rubiks Cube, it was easier!\nI found that the Rubiks cube and Linux are alike. Looks real confusing\nuntil you read the right book. :-)\n\t-- seen on c.o.l.misc, about the \"Linux Learning Curve\"",
  "> I've hacked the Xaw3d library to give you a Win95 like interface and it\n> is named Xaw95. You can replace your Xaw3d library.\nOh God, this is so disgusting!\n\t-- seen on c.o.l.development.apps, about the \"Win95 look-alike\"",
  "Besides, its really not worthwhile to use more than two times your physical\nram in swap (except in a select few situations). The performance of the system\nbecomes so abysmal you'd rather heat pins under your toenails while reciting\nWindows95 source code and staring at porn flicks of Bob Dole than actually try\nto type something.\n\t-- seen on c.o.l.development.system, about the size of the swap space",
  "> I get the following error messages at bootup, could anyone tell me\n> what they mean?\n> fcntl_setlk() called by process 51 (lpd) with broken flock() emulation\nThey mean that you have not read the documentation when upgrading the\nkernel.\n\t-- seen on c.o.l.misc",
  "Only wimps use tape backup: _real_ men just upload their important stuff\non ftp, and let the rest of the world mirror it ;)\n\t-- Linus Torvalds, about his failing hard drive on linux.cs.helsinki.fi",
  "One of the things that hamper Linux's climb to world domination is the\nshortage of bad Computer Role Playing Games, or CRaPGs. No operating system\ncan be considered respectable without one.\n\t-- Brian O'Donnell, odonnllb@tcd.ie",
  "The game, anoraks.2.0.0.tgz, will be available from sunsite until somebody\nresponsible notices it and deletes it, and shortly from\nftp.mee.tcd.ie/pub/Brian, though they don't know that yet.\n\t-- Brian O'Donnell, odonnllb@tcd.ie",
  "'Ooohh.. \"FreeBSD is faster over loopback, when compared to Linux\nover the wire\". Film at 11.'\n\t-- Linus Torvalds",
  "Q: Would you like to see the WINE list?\nA: What's on it, anything expensive?\nQ: No, just Solitaire and MineSweeper for now, but the WINE is free.\n\t-- Kevin M. Bealer, about the WINdows Emulator",
  "So in the future, one 'client' at a time or you'll be spending CPU time with\nlots of little 'child processes'.\n\t-- Kevin M. Bealer, commenting on the private life of a Linux nerd",
  "By the way, I can hardly feel sorry for you... All last night I had to listen\nto her tears, so great they were redirected to a stream.  What?  Of _course_\nyou didn't know.  You and your little group no longer have any permissions\naround here.  She changed her .lock files, too.\n\t-- Kevin M. Bealer, commenting on the private life of a Linux nerd",
  "We should start referring to processes which run in the background by their\ncorrect technical name... paenguins.\n\t-- Kevin M. Bealer, commenting on the penguin Linux logo",
  "We can use symlinks of course... syslogd would be a symlink to syslogp and\nftpd and ircd would be linked to ftpp and ircp... and of course the\npoint-to-point protocal paenguin.\n\t-- Kevin M. Bealer, commenting on the penguin Linux logo",
  "This is a logical analogy too... anyone who's been around, knows the world is\nrun by paenguins.  Always a paenguin behind the curtain, really getting things\ndone.  And paenguins in politics--who can deny it?\n\t-- Kevin M. Bealer, commenting on the penguin Linux logo",
  "Linux: Where Don't We Want To Go Today?\n\t-- Submitted by Pancrazio De Mauro, paraphrasing some well-known sales talk",
  "The most important design issue... is the fact that Linux is supposed to\nbe fun...\n\t-- Linus Torvalds at the First Dutch International Symposium on Linux",
  "In short, at least give the penguin a fair viewing. If you still don't\nlike it, that's ok: that's why I'm boss. I simply know better than you do.\n\t-- Linus \"what, me arrogant?\" Torvalds, on c.o.l.advocacy",
  "<SomeLamer> what's the difference between chattr and chmod?\n<SomeGuru> SomeLamer: man chattr > 1; man chmod > 2; diff -u 1 2 | less\n\t-- Seen on #linux on irc",
  "The linuX Files -- The Source is Out There.\n\t-- Sent in by Craig S. Bell, goat@aracnet.com",
  "\"... being a Linux user is sort of like living in a house inhabited\nby a large family of carpenters and architects. Every morning when\nyou wake up, the house is a little different. Maybe there is a new\nturret, or some walls have moved. Or perhaps someone has temporarily\nremoved the floor under your bed.\" - Unix for Dummies, 2nd Edition\n\t-- found in the .sig of Rob Riggs, rriggs@tesser.com",
  "C is quirky, flawed, and an enormous success\n\t-- Dennis M. Ritchie",
  "If Bill Gates is the Devil then Linus Torvalds must be the Messiah.\n\t-- Unknown source",
  "Vini, vidi, Linux!\n\t-- Unknown source",
  "Checking host system type...\ni586-unknown-linux\nconfigure: error: sorry, this is the gnu os, not linux\n\t-- Topic on #Linux",
  "It's easy to get on the internet and forget you have a life\n\t-- Topic on #LinuxGER",
  "To kick or not to kick...\n\t-- Somewhere on IRC, inspired by Shakespeare",
  "Linux - Where do you want to fly today?\n\t-- Unknown source",
  "The easiest way to get the root password is to become system admin.\n\t-- Unknown source",
  "The good thing about standards is that there are so many to choose from.\n\t-- Andrew S. Tanenbaum",
  "The primary difference [...] is that the Java program will reliably and\nobviously crash, whereas the C Program will do something obscure\n\t-- Java Language Tutorial",
  "LOAD \"LINUX\",8,1\n\t-- Topic on #LinuxGER",
  "Old MacLinus had a stack/l-i-n-u-x/and on this stack he had a trace/l-i-n-u-x\nwith an Oops-Oops here and an Oops-Oops there\nhere an Oops, there an Oops, everywhere an Oops-Oops.\n\t-- tjimenez@site.gmu.edu, linux.dev.kernel",
  "Also another major deciding factor is availability of source code.\nIt just gives everybody a warm fuzzy feeling knowing that there is\nsource code available to the product you are using.  It allows everybody\nto improve on the product and fix bugs etc. sooner than the author(s)\nwould get the time/chance to.\n\t-- Atif Khan",
  "> Also another major deciding factor is availability of source code.\n> It just gives everybody a warm fuzzy feeling knowing that there is\n> source code available to the product you are using.  It allows everybody\n> to improve on the product and fix bugs etc. sooner than the author(s)\n> would get the time/chance to.\n\nI think this is one the really BIG reasons for the snowball/onslaught\nof Linux and the wealth of stuff available that gets enhanced faster\nthan the real vendors can keep up.\n\t-- Norman",
  "Not only Guinness - Linux is good for you, too.\n\t-- Banzai on IRC",
  "> NE-2000 clone.  Pentium optimizing gcc (pentium gcc pl8 I think).\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\nBuild a kernel with the proper gcc. Reports with a non standard compiler\nare useless.\n\t-- Alan Cox",
  "BTW: I have a better name for the software .... Microsoft Internet\nExploder.\n\t-- George Bonser <grep@cris.com>",
  "Well, since MS can't be sure of the username of someone downloading\nthings, they are going to play it safe and have everything downloaded\nand executed by Explorer as suid root. That way, it will run on ANY\nsystem anywhere. :)\n\t-- George Bonser <grep@cris.com>",
  "If you really want pure ASCII, save it as text... or browse\nit with your favorite browser...\n\t-- Alexandre Maret <amaret@infomaniak.ch>",
  "Sorry for mailing this article, I've obviously made a typo (168!=186)\nthat's the price for being up all night and doing some \"quick\"\nchecks before you go to bed ....\n\t-- Herbert Rosmanith <herp@wildsau.idv.uni-linz.ac.at>",
  "Just to remind everyone.  Today, Sept 17, is Linux's 5th birthday.  So\nhappy birthday to all on the list.  Thanks go out to Linus and all the\nother hard-working maintainers for 5 wonderful fast paced years!\n\t-- William E. Roadcap <roadcapw@cfw.com>",
  "Exporting beer from Finnland doesn't seem to be that much of a hassle,\nas the Lenigrad Cowboys brought a lot of their brew to the concerts in\nAustria.\n\t-- Otmar Lendl <lendl@cosy.sbg.ac.at>",
  "Beeping is cute, if you are in the office ;)\n\t-- Alan Cox",
  ">  Where in the US is Linus?\n\nHe was in the \"Promise Land\".\n\t-- David S. Miller <davem@caip.rutgers.edu>",
  ">       Yeah, Linus is in the US.\n>\n>       His source trees are in Finland.\n\n        OK, someone give him access -fast- ...... ;-)\n\t-- babydr@nwrain.net, because of problems with the kernel",
  "Subject: Linux box finds it hard to wake up in the morning\n\nI've heard of dogs being like their owners, but Linux boxen?\n\t-- Peter Hunter <peter.hunter@blackfriars.oxford.ac.uk>",
  "Win 95 is simplified for the user:\n\nUser: What does this configuration thing do?\nYou: It allows you to modify your settings, for networking,\n        hardware, protocols, ...\nUser: Whoa! Layman's terms, please!\nYou:  It changes stuff.\nUser: That's what I'm looking for!  What can it change?\nYou:  This part changes IP forwarding.  It allows ...\nUser: Simplify, simplify!  What can it do for ME?\nYou:  Nothing, until you understand it.\nUser: Well it makes me uncomfortable.  It looks so technical;\n      Get rid of it, I want a system *I* can understand.\nYou:  But...\nUser: Hey, whose system is this anyway?\nYou:  (... rm this, rm that, rm /etc/* ...) \"All done.\"\n\t-- Kevin M. Bealer <kmb203@psu.edu>",
  "*** PUBLIC flooding detected from erikyyy\n<lewnie> THAT's an erik, pholx.... ;)\n\t-- Seen on #LinuxGER",
  "I've no idea when Linus is going to release 2.0.24, but if he takes\ntoo long Im going to release a 2.0.24unoff and he can sound off all\nhe likes.\n\t-- Alan Cox",
  "All the existing 2.0.x kernels are too buggy for 2.1.x to be the\nmain goal.\n\t-- Alan Cox",
  "Computers are useless.  They can only give you answers.\n\t-- Pablo Picasso",
  "martin@bdsi.com (no longer valid - where are you now, Martin?)\n\t-- from /usr/src/linux/drivers/cdrom/mcd.c",
  "[...] or some clown changed the chips on a board and not its name.\n(Don't laugh!  Look at the SMC etherpower for that.)\n\t-- from /usr/src/linux/MAINTAINERS",
  "REST:\nP:      Linus Torvalds\nS:      Buried alive in email\n\t-- from /usr/src/linux/MAINTAINERS",
  "         Why use Windows, when you can have air conditioning?\n         Why use Windows, when you can leave through the door?\n\t-- Konrad Blum",
  "Netscape is not a newsreader, and probably never shall be.\n\t-- Tom Christiansen",
  "I think it's time to remove Qt and Qt-derived applications from the\ndistribution.  By distributing it, we only encourage authors to create\nrestrictive licenses.\n\t-- Bruce Perens",
  "If someone can point me to a good and _FREE_ backup software that keeps\ntrack of which files get stored on which tape, we can change to it.\n\t-- Mike Neuffer, admin of i-Connect Corp.",
  "Whoa, first contact!\n\n[...]\n\nWelcome, from the people of Terra (Sol III). We extend our hands in\nfriendship, and sincerely hope you shall do the same with your\nhand-equivelents.\n\t\t-- Jason Burrell about a russian posting",
  "> Whoa, first contact!\n\nNope, 'fraid not, Linux is still primarily used on planet Earth, I'm\nafraid.\n\nOur friend here sent a message in Russian (KOI8-R encoding).\n\t\t-- Aleksey Kliger, explaining a russian posting",
  "There is, however, a strange, musty smell in the air that reminds me of\nsomething...hmm...yes...I've got it...there's a VMS nearby, or I'm a Blit.\n\t\t-- Larry Wall in Configure from the perl distribution",
  "1648 files (84%) out of the files that I mirror disappeared.  Since\nmy delete threshold was set at 90%, all those files are now missing\nfrom my hard drive.  It's going to take a loooong time to fetch those\nagain via 14.4kbps!\n\t\t-- Brian C. White",
  ">    What is the status of Linux' Unicode implementation. Will Linux\n>    be prepared for the first contact?\n\nWe have full klingon console support just in case\n\t\t-- Alan Cox on linux-kernel",
  "\"You, sir, are nothing but a pathetically lame salesdroid!\nI fart in your general direction!\"\n\t\t-- Randseed on #Linux",
  "* Jes wonders why so many people in here uses fooZZZZZ and foo_sleeping nicks\n<peter> Jes: Because they are sleeping?\n\t\t-- Seen on #Linux",
  "* gb notes that fdisk thinks his cdrom can store one terabyte\n\t\t-- Seen on #Linux",
  "Check it out, send me comments, and dance joyously in the streets,\n\t\t-- Linus Torvalds announcing 2.0.27",
  "AP/STT.  Helsinki, Dec 5th, 6:22 AM.  For immediate release.\n\nIn order to allay fears about the continuity of the Linux project, Linus\nTorvalds together with his manager Tove Monni have released \"Linus\nv2.0\", affectionately known as \"Kernel Hacker - The Next Generation\".\n\nLinux stock prices on Wall Street rose sharply after the announcement;\nas one well-known analyst who wishes to remain anonymous says - \"It\nshows a long-term commitment, and while we expect a short-term decrease\nin productivity, we feel that this solidifies the development in the\nlong run\".\n\nOther analysts downplay the importance of the event, and claim that just\nabout anybody could have done it.  \"I'm glad somebody finally told them\nabout the birds and the bees\" one sceptic comments cryptically.  But\neven the skeptics agree that it is an interesting turn of events.\n\nOthers bring up other issues with the new version - \"I'm especially\nintrigued by the fact that the new version is female, and look forward\nto seeing what the impact of that will be on future development.  Will\n\"Red Hat Linux\" change to \"Pink Hat Linux\", for example?\"\n\t-- Linus Torvalds announcing that he became father of a girl",
  "Sex dumps core\n(Sex is a Simple editor for X11)\n\t-- Seen on debian bugtracking",
  "I tried the clone syscall on me, but it didn't work.\n\t-- Mike Neuffer trying to fix a serious time problem",
  "-  long    f_ffree;    /* free file nodes in fs */\n+  long    f_ffree;    /* freie Dateiknoten im Dateisystem */\n\t-- Seen in a translation",
  "* Phaedrus wishes he could get a machine that consists of Sparc IO,\n  Alpha Processors and sleek design of an SGI\n<pp> And intel prices\n\t-- Seen on #Linux",
  "<Tazman> damn my office is cold.\n<Tazman> need a hot secretary to warm it up.\n\t-- Seen on #Linux",
  "This is a scsi driver, scraes the shit out of me, therefore I tapdanced\nand wrote a unix clone around it (C) by linus\n\t-- Somewhere in the kernel tree",
  " *  This is complicated.  Has to do with interrupts.  Thus, I am\n *  scared witless.  Therefore I refuse to write this function. :-P\n\t-- From the maclinux patch",
  "Yes I have a Machintosh, please don't scream at me.\n\t-- Larry Blumette on linux-kernel",
  "<miguel> any new sendmail hole I have to fix before going on vacations?\n\t-- Seen on #Linux",
  "AUTHOR\nFvwmAuto just appeared one day, nobody knows how.\n\t-- FvwmAuto(1x)",
  "<lilo> Fairlight: udp is the light margarine of tcp/ip transport protocols :)\n\t-- Seen on #Linux",
  "I don't even know if it makes sense at all :) This is an experimental patch\nfor an experimental kernel :))\n\t-- Ingo Molnar on linux-kernel",
  "Linux - Das System fuer schlaue Maedchen ;)\n\t-- banshee",
  "If loving linux is wrong, I don't wanna be right.\n\t-- Topic for #LinuxGER",
  ">>> FreeOS is an english-centric name\n\nHave you all been stuck in email, or have any of you tried\n*pronouncing* that? free-oh-ess? free-ows? fritos? :-)\n\t-- Mark Eichin",
  "The documentation is in Japanese.  Good luck.\n\t-- Rich $alz",
  "People are going to scream bloody murder about that.\n\t-- Seen on linux-kernel",
  ">   1. is qmail as secure as they say?\n\nDepends on what they were saying, but most likely yes.\n\t-- Seen on debian-devel",
  "NEVER RESPOND TO CRITICAL PRESS.  IT IS A GAME YOU CAN ONLY LOSE, AND IT\nMAKES US LOOK BAD.\n\t-- Bruce Perens",
  "A feature is nothing more than a bug with seniority.\n\t-- Unknown source",
  "Winnuke in one line?  No problem:\nperl -MIO::Socket -e \\\n'IO::Socket::INET->new(PeerAddr=>\"bad.dude.com:139\")->send(\"bye\",MSG_OOB)'\n\nAnd formatted so it's a little easier to read:\n\n        #!/usr/bin/perl\n        use IO::Socket;\n        IO::Socket::INET\n                ->new(PeerAddr=>\"bad.dude.com:139\")\n                ->send(\"bye\", MSG_OOB);\n\n\t\t-- Randal Schwartz",
  "If a 'train station' is where a train stops, what's a 'workstation'?",
  "\"We don't do a new version to fix bugs.\" - Bill Gates\n\"The new version - it's not there to fix bugs.\" - Bill Gates\n\t-- Retranslated from Focus 43/1995, pp. 206-212",
  "The POP3 server service depends on the SMTP server service, which\nfailed to start because of the following error:\nThe operation completed successfully.\n\t-- Windows NT Server v3.51",
  "Software is like sex; it's better when it's free.\n\t-- Linus Torvalds",
  "vi is [[13~^[[15~^[[15~^[[19~^[[18~^ a\nmuk[^[[29~^[[34~^[[26~^[[32~^ch better editor than this emacs. I know\nI^[[14~'ll get flamed for this but the truth has to be\nsaid. ^[[D^[[D^[[D^[[D ^[[D^[^[[D^[[D^[[B^\nexit ^X^C quit :x :wq dang it :w:w:w :x ^C^C^Z^D\n\t-- Jesper Lauridsen <rorschak@daimi.aau.dk> from alt.religion.emacs",
  "oh okay. my mistake.\n\nYafcot:atj(*),\n\nmark\n\n* Yet another fool coming over this: according to joey\n\t-- mark@mail.novare.net",
  "Sorry.  I just realized this sentance makes no sense :)\n\t-- Ian Main",
  "Stopping Apache webserver...sleeping...starting again...\napache: dl-version.c:189:\n _dl_check_map_versions: Assertion `needed != ((void *)0)' failed\nnoooooooooooooooooooooooooooo\n\t-- netgod on #Debian at LISC",
  "Make it idiot-proof, and someone will breed a better idiot.\n\t-- Oliver Elphick",
  "#Debian makes me feel all warm and fuzzy inside. :)\n\t-- HippieGuy on #Debian",
  "<Myxie> I know. Unless htere is a cookie monster somewhere between us tat\nmuches the amil.\n<Myxie> amil/mail\n<Myxie> muches/munches tat/that htere/there\n<HippieGuy> heheh\n<HippieGuy> problems? :)\n* Myxie needs an ircii addon that pipes teh command line through ispell :)\n\t-- Seen on #Debian",
  "ECRC hat keine lynx komp. seiten, sowas MUSS ja pleite gehen ;-)=\n\t-- Getty on #LinuxGER",
  "Uh... deity is a word, and diety isn't.\n\nOr is it supposed to be one of those recursive acronyms?  Diety Is\nExcellent To You.  Deity Eats Icecream That's Yellow.  Diety Is\nEloping To Yokohama.  I'll stop now.\n\t-- Guy Maor",
  "Why are there always boycotts?  Shouldn't there be girlcotts too?\n\t-- argon on #Linux",
  "<sct> Anyone want the new supermount? :)\n<klogd> whats new about it\n<sct> klogd: It cleans whiter than white. :)\n\t-- Seen on #Linux",
  "Und die Tastaturabrdücke auf Ihrer Wange unterstreichen seeeeeehr\nvorteilhaft ihr unterschütterliches Vertrauen in die moderene\nTechnologie\n\t-- Agent Gully in \"Die eXakten\"",
  "- DDD no longer requires the librx library.  Consequently, librx\n  errors can no more cause DDD to crash.\n\t-- DDD",
  "snafu = Situation Normal All F%$*ed up",
  "It's computer hardware, of course it's worth having <g>\n\t-- Espy on #Debian",
  "Alan E. Davis: Some files at llug.sep.bnl.gov/pub/debian/Incoming are\nstamped on 10 January 1998.  As I write, nowhere on Earth is it now 10 January.\n\nCraig Sanders: That just proves how advanced debian is, doesn't it :-)\n\t-- debian-devel",
  "Computers are like air conditioners.  Both stop working, if you open windows.\n\t-- Adam Heath",
  "I am NOT a kludge!  I am a computer!\n\t-- tts",
  "<Joey> gorgo: *lol*\n<gorgo> joey: what's so funny? :)\n<Culus> shh, joey is losing all sanity from lack of sleep\n<Culus> 'yes joey, very funny'\n<Culus> Humor him :>\n\t-- Seen on #Debian",
  "* SynrG notes that the number of configuration questions to answer in sendmail\n  is NON-TRIVIAL\n\t-- Seen on #Debian",
  "My apologies if I sound angry.  I feel like I'm talking to a void.\n\t-- Avery Pennarun",
  "RIP is irrelevant.  Spoofing is futile.  Your routes will be aggregated.\n\t-- Alex Yuriev",
  "After 14 non-maintainer releases, I'm the S-Lang non-maintainer.\n\t-- Ray Dassen",
  "BREAKFAST.COM Halted... Cereal Port Not Responding.",
  "* JHM wonders what Joey did to earn \"I'd just like to say, for the record,\n  that Joey rules.\"\n\t-- Seen on #Debian",
  "Steal my cash, car and TV - but leave the computer!\n\t-- Soenke Lange <soenke@escher.north.de>",
  "The only really good reason I can think to not release specs is\nembarrassment on just how crappy some hardware out there is, or just how\nbuggy it is.\n\t-- Chris Wedgwood <cw@ix.net.nz>",
  "> Alan Cox wrote:\n[..]\n\nNo I didn't.  Someone else wrote that.  Please keep attributions\nstraight.\n\t-- From linux-kernel",
  "Do people like check the Debian website every 5 minutes to check it hasn't\nmorphed into another one?\nNot that I'm one to talk, but some people seriously need to get a life\n\t-- james on #Debian",
  "... Linux und seine Programme sind damit so etwas wie ein real existierender\nSozialismus der besseren Art ...\n\t-- Christian Seel in der Berliner Morgenpost v. 9.3.1997",
  "* james would be more impressed if netgod's magic powers could stop the splits\nin the first place...\n* netgod notes debian developers are notoriously hard to impress\n\t-- Seen on #Debian",
  "   * In anticipation of 2.10.02 release, updated to patchlevel\n     +ircu2.10.01+.config6-7.config7-8.lgline3.iwho.limit.glibc.motdcache2.\n     trace.whois1-2.config8-9.statsw.sprintf2-3.msgtree2.memleak1-2+.\n     msgtree2-3.gline8-9.gline9-10.invite2.rbr.stats.numclients.whisper.\n     whisper1-2.stats1-2.nokick1-2.chroot.config9-11.snomask7-8.limi+t1-3.\n     userip1-3.userip3-4.config11-12.config12-13.umode2-3.akillsbt.who4-5.\n     kn.kn1-2.freebsdcore2.msgtree3-5.y2k.glibc1-2.rmfunc.msgf+lags2.\n     who5-6.nickchange2.glibc2-3.modeless3\n\t-- From the annoucement of ircd 2.10.01-3 for Debian GNU/Linux",
  "* Joey should not write changelog entries at 5:30am\n<Joey>    * DFSC Free cgi library\n<Joey> What's that? DFSC?\n<jim> Debian Free Software mroooooCows\n\t-- Seen on #Debian",
  "<posix> this guy _is_ crazy\n<stargazer> posix: from the looks of Enlightenment he's on LSD\n<posix> LSD is nothing compared to what this guy's on..\n\t-- Seen on #Unix",
  "On Netscape GPLing their browser: ``How can you trust a browser that\nANYONE can hack? For the secure choice, choose Microsoft.''\n\t-- <oryx@pobox.com> in a comment on slashdot.org",
  "Turn right here. No! NO! The OTHER right!",
  "#define FALSE   0               /* This is the naked Truth */\n#define TRUE    1               /* and this is the Light */\n\t-- mailto.c",
  "<Stealth> How do I bind a computer to an NIS server?\n<Joey> Use a rope?\n\t-- Seen on #Debian",
  "Try to remove the color-problem by restarting your computer several times.\n\t-- Microsoft-Internet Explorer README.TXT",
  "Does biff in bo work\ncoz it biffin doesn't beep\nan if biff in bo is broke\nthen biff in bo I will delete\n\nI've tried biff in bo with 'y'\nI've tried biff in bo with '-y'\nno biffin output does it show\nso poor wee biff is gonna go.\n\t-- John Spence <jspence@lynx.net.au> on debian-user",
  "Real Men don't make backups.  They upload it via ftp and let the world mirror\nit.\n\t-- Linus Torvalds",
  "One tree to rule them all,\nOne tree to find them,\nOne tree to bring them all,\nand to itself bind them.\n\t-- Gavin Koch <gavin@cygnus.com>",
  "As I currently don't have a floppy drive in my computer, I'd like to\nmake an `emergency cdrom' ;)\n\t-- Eugene Crosser <crosser@average.org>",
  "Alan Cox wrote:\n>> On any procmail new enough not to be full of security holes you set\n>Brain on, Imeant majordomo of course 8)\nYou got me worried there for a brief (very brief) moment :-).\n\t-- Stephen R. van den Berg (AKA BuGless)",
  "<grin> seen jhm\n<dpkg> jhm is Sarek, and jhm is on the channel right now!\n* JHM wonders why dpkg remembers that particular nick.\n<grin> dpkg: Sarek? ermm, sure, and I am Khan\n\t-- Seen on #Debian",
  "When you have 200 programmers trying to write code for one\nproduct, like Win95 or NT, what you get is a multiple personality\nprogram.  By definition, the real problem is that these programs are\npsychotic by nature and make people crazy when they use them.\n\t-- Joan Brewer on alt.destroy.microsoft",
  "<igor> Hah! we have 2 Johnie Ingrams in the channel :)\n<igor> Hey all btw :)",
  "I just uploaded xtoolplaces-1.6. It fixes all bugs but one: It still\ncoredumps instead of doing something useful.  The upstream author's\ne-mail address bounces, Redhat doesn't provide it and I never used it.\n\t-- Sven Rudolph <sr1@os.inf.tu-dresden.de>",
  "> I thing you're missing the capability of Makefiles.\n\n        It takes several _hours_ to do `make' a second time on my\nmachine with the latest glibc sources (and no files are recompiled a\nsecond time).  I think I'll remove `build' after changing one file if\nI want to recompile it.\n\t\t-- Juan Cespedes <cespedes@debian.org>",
  "<Culus> aIIIIIIIIIII!!!!!!!!!!!!!!!11\n<Culus> MY LIGHT JUST DIED\n<Culus> I AM SO SAD\n<Culus> I'm blind! I'm blind!\n<dark> Light?\n<dark> Turn all your xterms to black-on-white :)  Plenty of light that way.\n\t-- Seen on #Debian",
  "| |-sshd---tcsh-+-dpkg-buildpacka---rules---sh---make---make---sh\n---make---sh---make---sh---make---sh---make---sh---make\n\t-- While packaging XFree86 for Debian GNU/Linux",
  "/*\n *     Please skip to the bottom of this file if you ate lunch recently\n *                             -- Alan\n */\n\t-- from Linux kernel pre-2.1.91-1",
  "#if _FP_W_TYPE_SIZE < 64\n#error \"Only stud muffins allowed, schmuck.\"\n#endif\n\t-- linux/arch/sparc64/quad.c",
  "#if _FP_W_TYPE_SIZE < 32\n#error \"Here's a nickel kid.  Go buy yourself a real computer.\"\n#endif\n\t-- linux/arch/sparc64/double.h",
  "<dark> eat Depends: cook | eat-out.\n       But eat-out is non-free so that's out.\n       And cook Recommends: clean-pans.\n\t-- Seen on #Debian",
  "* Linux Viruscan.....\n  Windows 95 found.  Remove it? (Y/y)\n\t-- Unknown source",
  "<sel> need help: my first packet to my provider gets lost :-(\n<netgod> sel:  don't send the first one, start with #2\n* netgod is kidding",
  "These download files are in Microsoft Word 6.0 format. After\nunzipping, these files can be viewed in any text editor, including\nall versions of Microsoft Word, WordPad, and Microsoft Word Viewer\n\t\t-- From Micro$oft",
  "Ooh, mommy, mommy, what I have now doesn't work in this extremely\nunlikely circumstance, so I'll just throw it away and write something\ncompletely new.\n\t\t-- Linus Torvalds",
  "#ifdef __SMP__\n#error \"Me no hablo Alpha SMP\"\n#else\n#define irq_enter(cpu, irq)     (++local_irq_count[cpu])\n#define irq_exit(cpu, irq)      (--local_irq_count[cpu])\n#endif\n\t-- from kernel 2.1.90, arch/alpha/kernel/irc.c",
  "Linus Torvalds:\n> This is the special Easter release of linux, more mundanely called 1.3.84\nWinfried Truemper:\n> Umh, oh. What do you mean by \"special easter release\"?. Will it quit\n> working today and rise on easter?",
  "I never thought that I'd see the day where Netscape is free software and\nX11 is proprietary.  We live in interesting times.\n\t-- Matt Kimball <mkimball@xmission.com>",
  "Because I don't need to worry about finances I can ignore Microsoft\nand take over the (computing) world from the grassroots.\n\t-- Linus Torvalds",
  "/*\n * Buddy system. Hairy. You really aren't expected to understand this\n *\n */\n\t-- From /usr/src/linux/mm/page_alloc.cA",
  "baz bat bamus batis bant.\n\t-- James Troup",
  "Just go ahead and write your own multitasking multiuser os!\nWorked for me all the times.\n\t-- Linus Torvalds",
  "I've seen people with new children before, they go from ultra happy to\nlooking like something out of a zombie film in about a week.\n\t-- Alan Cox about Linus after his 2nd daughter",
  "I expect that no one has objections.  However, if I'd only add these entries\nto the list because `I think it's the right thing to do', I'd get a lot of\nflames afterwards :)\n\t-- Christian Schwarz",
  "Various documentation updates and bugfixes (the best way to know that a\nstable kernel is approaching is to notice that somebody starts to\nspellcheck the kernel - it has so far never failed)\n\t-- Linus Torvalds in the annoucement for pre-2.1.99-3",
  "You will not censor me through bug terrorism.\n\t-- James Troup",
  "<doogie> Thinking is dangerous.  It leads to ideas.\n\t-- Seen on #Debian",
  "<james> Are we going to make an emacs out of apt?\n        APT - Debian in a program.  It even does your laundry\n\t-- Seen on #Debian",
  "<joost> Do you mean to say that I can read mail with vi too? ;-)\n<Joey> Didn't you know that?\n<Joey> :r /var/spool/mail/jk\n\t-- debian-mentors",
  "Charles Briscoe-Smith <cpbs@debian.org>:\n  After all, the gzip package is called `gzip', not `libz-bin'...\n\nJames Troup <troup@debian.org>:\n  Uh, probably because the gzip binary doesn't come from the\n  non-existent libz package or the existent zlib package.\n\t-- debian-bugs-dist",
  "Debian is like Suse with yast turned off, just better. :)\n\t-- Goswin Brederlow",
  "The truth is not free.  It's that simple.  If you change the truth, it is no\nlonger true - so the truth is not free!\n\t-- Jules Bean about freeness of documentation",
  "<jim> Lemme make sure I'm not wasting time here... bcwhite will remove\n      pkgs that havent been fixed that have outstanding bugs of severity\n      \"important\".  True or false?\n<JHM> jim: \"important\" or higher.  True.\n<jim> Then we're about to lose ftp.debian.org and dpkg :)\n* netgod will miss dpkg -- it was occasionally useful\n<Joey> We still have rpm....\n\t-- Seen on #Debian",
  "The problem here (as someon else stated) is that when multiple dists\nuse the same package format it only gives a \"false sense of compatibility\".\n\t-- Stephen Carpenter <sjc@delphi.com>",
  "*** Rince is wagner@schizo.DAINet.de (We have Joey, we have Fun, we have Linux\non a Sun)\n\t-- Seen on #Debian",
  "... Linux und seine Programme sind damit\nso etwas wie ein real existierender Sozialismus der besseren Art...\n\t-- Christian Seel in der Berliner Morgenpost v. 9.3.1997",
  "The most effective has probably been Linux/8086 - that was a joke\nthat got out of hand.  So far out of hand in fact its almost approaching\nusability because other folks thought it worth doing - Alistair Riddoch\nespecially.\n\t-- Alan Cox",
  "The only other people who might benefit from Linux8086 would be owners\nof PDP/11's and other roomsized computers from the same era.\n\t-- Alan Cox",
  "Ha. I say let them try -- even vi+perl couldn't match the power of an\neditor which is, after all, its own OS.  ;-)\n\t-- Johnie Ingram on debian-devel, about linking vim with libperl.so",
  "Being overloaded is the sign of a true Debian maintainer.\n\t-- JHM on #Debian",
  "<alaint> joey--very clever !!!\n<alaint> joey--no wonder that Debian is a good distrib with coder like you\n\t-- Seen on #Debian (referring to my RAID article for the LJ)",
  "There are 3 kinds of people: those who can count & those who can't.\n\t-- Unknown source",
  "Despite the best efforts of a quantum bigfoot drive (yes I know everyone\ntold me they suck, now I know they were right) 2.1.109ac1 is now available\n\t-- Alan Cox announcing Linux 2.1.109ac1",
  "<dark> Turns out that grep returns error code 1 when there are no matches.\n       I KNEW that.  Why did it take me half an hour?\n\t-- Seen on #Debian",
  "It's simply unbelievable how much energy and creativity people have\ninvested into creating contradictory, bogus and stupid licenses...\n\t--- Sven Rudolph about licences in debian/non-free.",
  "<Overfiend> partycle: I seriously do need a vacation from this\n            package.  I actually had a DREAM about introducing a\n            stupid new bug into xbase-preinst last night.  That's a\n            Bad Sign.\n\t-- Seen on #Debian shortly before the release of Debian 2.0",
  "<core> i'm glad Debian finally got into\n        polar-deep-freeze-we-arent-shitting-you state finally.\n\t-- Seen on #Debian shortly before the release of Debian 2.0",
  "<dark> Looks like the channel is back to normal :)\n<jim> You mean it's not scrolling faster than anyone can read? :)\n\t-- Seen on #Debian after the release of Debian 2.0",
  "Alex Buell:\nOr how about a Penguin logo painted in really really trippy\ncolours, and emblazoned with the word LSD. :o)\n\nGeert Uytterhoeven:\nWe already had that one, but unfortunately Russell King fixed that nasty\npalette bug in drivers/video/fbcon.c :-)\n\t-- linux-kernel",
  "Writing non-free software is not an ethically legitimate activity,\nso if people who do this run into trouble, that's good!  All businesses\nbased on non-free software ought to fail, and the sooner the better.\n\t-- Richard Stallman",
  "Außerdem noch [..] die Distribution für Puristen, denen technische\nEleganz und Qualität und philosophisch reine Lehre der `freien Software'\nüber totale Einfachheit geht (Debian) und viele mehr.\n\t-- Anselm Lingnau in de.comp.os.unix.discussion",
  "Fehlermeldung von StarOffice:\n\nDas Dokument wurde fuer den Drucker Generic PostScript Printer formatiert.\nDer Drucker ist nicht vorhanden.  Soll der Standarddrucker Generic\nPostScript Printer verwendet werden?\n\nOb Programme schizophren werden koennen?\n\t-- Oliver Bedford <O.Bedford@uni-koeln.de>",
  "No, that's wrong too.  Now there's a race condition between the rm and\nthe mv.  Hmm, I need more coffee.\n\t-- Guy Maor on Debian Bug#25228",
  "Perhaps the RBLing (Realtime Black Hole) of msn.com recently, which\nprevented a large amount of mail going out for about 4 days, has had a\npositive influence in Redmond.  They did agree to work on their anti-relay\ncapabilities at their POPs to get the RBL lifted.\n\t-- Bill Campbell on Smail3-users",
  "Microsoft DNS service terminates abnormally when it receives a response\nto a DNS query that was never made.  Fix Information: Run your DNS\nservice on a different platform.\n\t-- bugtraq",
  "I am amazed that no-one's based a commercial distribution on Debian\nyet - it is by far the most solid UNIX-like OS I've ever installed,\nand I've played with HP/UX, Solaris, FreeBSD, BSDi, and SCO (not to\nmention OS/2, Novell, Win95/NT)\n\t-- Nathan E. Norman",
  "Jim>   http://www.novare.net/~eam/kaffe/\nJoey>                           ^\nJoey> And now we all learn how to write Ean's name and the URL is complete.\nJim> Hah!  I noticed that the instead I sent it, and I tried to hit ^g, but\n     I was too slow.  :-)\n\t--- debian-devel",
  "Die TeX-Artikel [..] aber doch inzwischen wohl nicht mehr an den\nFingern zweier Hände abzählbar (außer vielleicht von Informatikern,\ndie bekanntlich mit den Fingern bis 1023 zählen können.\n\t-- Anselm Lingnau",
  "And Bruce is effectively building BruceIX\n\t-- Alan Cox",
  "<Culus-> I will be known as Ian Black, Ean can be Ian Red, Netgod Ian Blue,\n         Che gets Ian Yellow, CQ is Ian Purple and Joey is Ian Indigo\n\t-- Some #Debian channel",
  "When a float occurs on the same page as the start of a supertabular\nyou can expect unexpected results.\n\t-- Documentation of supertabular.sty",
  "From: Ean Schuessler <ean@novare.net>\nThe unrecognized minister of propaganda,\nE\n\t-- Debian, joking",
  "* liw prefers not to have Linus run Debian, because then /me would\n  have to run Red Hat, just to keep the power balance :)\n\t-- #Debian",
  "<\\\\swing> and if we're playing old distributions... whatever happened to\nYggdrasil? :)\n<joost> \\\\swing: everybody who tried to pronounce it got their tongue in a knot\nand choked\n\t-- #Debian",
  "I'm telling you that the kernel is stable not because it's a kernel,\nbut because I refuse to listen to arguments like this.\n\t-- Linus Torvalds",
  "> Tut mir Leid, Jost, aber Du bist ein unertraeglicher Troll.\nWas soll das? Du *beleidigst* die Trolle!\n\t-- de.comp.os.unix.linux.misc",
  "Wenn also die KDE-Arbeit nochmal gemacht wird bei GNOME, hat das die\nEntwicklungszeit für ein freies Desktop-System verkürzt.  Hast Du auch\nirgendwo die passende Algebra zu der Rechnung?\n\t-- Sascha Ziemann in de.comp.os.unix.linux.misc",
  "* dpkg ponders: 'C++' should have been called 'D'\n\t-- #Debian",
  "<rm_-rf_> The real value of KDE is that they inspired and push the\n          development of GNOME :-)\n\t-- #Debian",
  "* dpkg hands stu a huge glass of vbeer\n* Joey takes the beer from stu, you're too young ;)\n* Cylord takes the beer from Joey, you're too drunk.\n* Cylord gives the beer to muggles.\n\t-- #Debian, celebrating the 5th anniversary",
  "<stu> Stupid nick highlighting\n<stu> Whenever someone starts with \"stupid\" it highlights the nick.  Hmm.\n\t-- #Debian",
  "<netgod> And once Diziet/CQ make the formal announcment that LSA\n         sucks, we can even reduce the Crisis Level rating and move\n         on to linuxfoundation.org.\n\t-- #Debian",
  "* LG loves czech girls.\n<vincent> LG: do they have additional interesting \"features\" other girls don't\nhave? ;)\n\t-- #Debian",
  "The first is to ensure your partner understands that nature has root\nprivileges - nature doesn't have to make sense.\n\t-- Telsa Gwynne",
  "As to house maintenance, does it involve problem solfing?  If so,\nyour hacker can safely be left to deall with the panning (for the\nmusement value, if nothering ese).\n\t-- Telsa Gwynne",
  "Remember: While root can do most everything, there are certain\nprivileges that only a partner can grant.\n\t-- Telsa Gwynne",
  "<Skyhook> Where is 'bavaria' proper?  I thought it was austria.\n\t-- Seen on #Linux",
  "Day X+4 months: Microsoft ships NT 5.0 for Intel.with a big media\n                event on TV. IBM begins to ship Debian 4.6 as the\n                standard OS on all machines from mainframe to PC\n                and announces the move on Slashdot.\n\t-- Christoph Lameter",
  "How many chunks could checkchunk check if checkchunk could check chunks?\n\t-- Alan Cox",
  "Q: How does a Unix guru have sex?\nA: unzip;strip;touch;finger;mount;fsck;more;yes;umount;sleep\n\t-- unknown source",
  "Someone on IRC was very sad about the uptime of his machine wrapping\nfrom 497 days to 0.\n\t-- linux-kernel",
  "<doogie> netgod:  8:42pm is not late.\n<netgod> doogie: its 2:42am in Joeyland\n\t-- #Debian",
  "We knew from experience that the essence of communal computing, as\nsupplied by remote-access, time-shared machines, is not just to type\nprograms into a terminal instead of a keypunch, but to encourage close\ncommunication.\n\t-- Dennis Ritchie",
  "modconf (0.2.37) stable unstable; urgency=medium\n  [...]\n  * Eduard Bloch:\n    - fixed Makefile broken Marcin Owsiany a while ago. The default manpage\n      has been overwritten with the polish translation. I still wonder why\n      nobody noticed this before. Closes: #117474\n  [...]\n -- Eduard Bloch <blade@debian.org>  Sun, 28 Oct 2001 12:53:27 +0100",
  "Could somebody drag the Irix team kicking and screaming into the 1980's,\nplease?\n\nI realize it might be quite painful for them, but maybe you could buy them\na disco tape, so they'd feel a little bit more at home.\n\n\t\t-- Linus \"Stayin' alive, stayin' alive\" Torvalds",
  "> <magical +3 sigh of hyperbole deflection>\n\nThe branden dodges your magical sigh. The branden attacks you with a\nslew of words! The branden misses!\n\n\t-- Henning Makholm in <yahsmr7dk9k.fsf@pc-043.diku.dk>",
  "<<<\nWhy Eclipse doesn't belong to the \"right\" tools? My naive understanding is\nthat Eclipse is the Emacs of the 21st century – it is open source, customizable\netc., similar to Emacs; in addition to being graphical.\n>>>\n\nThank you! I was wondering why I hated Eclipse so much, and you have put your\nfinger on it. It's exactly like a 21st century Emacs.\n\n    -- Shachar Shemesh\n    -- Re: [Haifux] [W2L] Call for lecturer + \"Linux guru\"\n       ( https://is.gd/PbULJR )",
  "Emacs is a nice operating system, but what it lacks, in order to compete with\nLinux, is a good text editor.\n    — based on https://en.wikiquote.org/wiki/Emacs",
  "> > You can easily install the binary distribution of Mozilla (from\n> > mozilla.org) on a different prefix, possibly under your home directory.\n> > Please install it and use it instead of Mozilla 1.1, at least when\n> > verifying if problems indeed exist. I do not wish to tolerate any more\n> > reports of problems when using Mozilla 1.1, because I can't tell if it's a\n> > bug that was fixed by then, or if it's an actual issue with Mozilla.\n> >\n> > On a slightly different note: my machine crashed the other day when\n> > using it with kernel 2.6.0. Can anyone help?\n>\n> I do not wish to tolerate any reports of problems when using kernel\n> 2.6.0, because I can't tell if it's a bug that was fixed by then, or\n> if it's an actual issue with the kernel.\n\nMy Commodore 64 is suffering from slowness and insufficiency of memory;\nand its display device is grievously short of pixels. Can anyone help?\n\n    -- Shlomi Fish, Muli Ben Yehuda and Omer Zak on discussions@hamakor.org.il.\n    -- https://is.gd/tAZmZD",
  "Who wants to remember that escape-x-alt-control-left shift-b puts you into\nsuper-edit-debug-compile mode?\n\n    -- Discussion in comp.os.linux.misc on the intuitiveness of commands,\n       especially Emacs.",
  "I've heard a Jew and a Muslim argue in a Damascus cafe with less passion\nthan the emacs wars.\"\n\t\t-- Ronald Florence <ron@18james.com> in\n\t\t   <ueu1c4mbrc.fsf@auda.18james.com>",
  "World domination.  Fast\n\n    -- Linus Torvalds ( Unsourced )",
  "Actually, typing random strings in the Finder does the equivalent of\nfilename completion.\n    -- Discussion in comp.os.linux.misc on the intuitiveness of commands: file\n       completion vs. the Mac Finder.",
  "Anyone who thinks UNIX is intuitive should be forced to write 5000 lines of\ncode using nothing but vi or emacs. AAAAACK!\n(Discussion in comp.os.linux.misc on the intuitiveness of commands, especially\nEmacs.)",
  "It's God.  No, not Richard Stallman, or Linus Torvalds, but God.\n\n    -- Matt Welsh",
  "There are no threads in a.b.p.erotica,  so there's no  gain in using a\nthreaded news reader.\n\n    -- Unknown source",
  "Running Windows on a Pentium is like having a brand new Porsche but only\nbe able to drive backwards with the handbrake on.\n\n    -- Unknown source",
  "The nice thing about Windows is - It does not just crash, it displays a\ndialog box and lets you press 'OK' first.\n\n    -- Arno Schaefer's .sig",
  "What's this script do?\n    unzip ; touch ; finger ; mount ; gasp ; yes ; umount ; sleep\nHint for the answer: not everything is computer-oriented. Sometimes you're\nin a sleeping bag, camping out.\n\n    -- (Contributed by Frans van der Zande.)",
  "Linux: Because Software Problems Should Not Cost Money.\n\n    -- Shlomi Fish\n    -- https://www.shlomifish.org/art/linux_banner/",
  "My friend Botje from freenode noted that some people on its #osdev chatroom,\nhave implemented kernels from scratch, which supported enough of POSIX to\nbootstrap a GNU ( https://gnu.org/ ) system (as I suspected).\n\nNow try this with CSS2.1...\n\n    -- Shlomi Fish\n    -- https://twitter.com/shlomif/status/1542047869989011457",
  "You know who's dumb? It's me. I'm dumb.\nI couldn't eject the tape.\nBecause there was no tape.\nAnd I was looking at the slot cover.\n\n    -- Jason B.",
  "Did I test the above macro? Don't be silly. All my code works on first\ntry. Except when it doesn't.\n\n    -- Linus Torvalds",
  "If I wanted made-up random crap and hallucinations, I'd ask ChatGPT,\nnot my filesystem.\n\n    -- Linus Torvalds"
];
