/**
 * @file The ChRIS backend's help: a page for each command it registers.
 *
 * The core's own commands keep their pages in `builtins/help.ts`; these are
 * registered with the ChRIS commands, so a session without ChRIS has none.
 *
 * @module
 */
import type { CommandHelp } from '../core/commandRegistry.js';

/**
 * Standard subcommands and options injected into every resource help entry.
 * Captures the Resource Contract documented in CONTEXT.md.
 */
export const RESOURCE_LIST_OPTIONS: string[] = [
  '',
  'STANDARD SUBCOMMANDS:',
  '  list              List resources (default: 20 per page)',
  '  search <term>     Search resources (alias: list --search <term>)',
  '  inspect           List available field names',
  '',
  'STANDARD OPTIONS:',
  '  --all             Fetch all pages',
  '  --limit <n>       Page size (default: 20)',
  '  --fields <f,f>    Columns to display',
  '  --sort <field>    Sort by field',
  '  --reverse         Reverse sort order',
  '  --table           Tabular output',
  '  --csv             CSV output',
];

/** The help for each ChRIS command, by name. */
export const chrisHelp: Record<string, CommandHelp> = {
  user: {
    usage: 'user <add|inspect|disable|enable|remove> <username>',
    description: 'Manage CUBE-local accounts; federated identities remain externally managed',
    options: ['Use `sudo user …` for lifecycle operations.', 'add prompts for email and a hidden password confirmation.'],
    examples: ['sudo user add jack.bivowac', 'sudo user disable jack.bivowac', 'sudo user remove jack.bivowac'],
  },
  netstat: {
    usage: 'netstat [-n <count>] [-r]',
    description: 'What the session has asked of CUBE: requests since the session (or the last reset), by endpoint family with the time spent, and the last few timed',
    options: [
      '-n <count>   List that many recent requests (default 10)',
      '-r, --reset  Forget the count after showing it',
    ],
    examples: [
      'netstat              # the count, by family, the last 10',
      'netstat -n 30        # the last 30 requests, timed',
      'netstat -r; cd ~/feeds; netstat   # what one navigation costs',
    ],
  },
  edit: {
    usage: 'edit <file>',
    description: 'Edit a ChRIS file in $EDITOR — fetches, opens, saves back on write',
    options: [
      'Uses $EDITOR (or $VISUAL, or vi as fallback)',
      'No-ops if file is unchanged on exit',
      'On save: deletes original and re-uploads — file path preserved, ID changes',
      'On upload failure: edited content preserved in /tmp',
    ],
    examples: [
      'edit /home/chris/uploads/config.yaml',
      'edit notes.txt',
      'EDITOR=nano edit report.json',
    ],
  },
  setfacl: {
    usage: 'setfacl -m u:<user>:r|g:<group>:r|o::r|o::- <path>... | setfacl -x u:<user>|g:<group> <path>...',
    summary: 'Share a feed with a user, a group or everyone, or stop sharing it',
    description:
      'A feed\'s access list, as POSIX ACL entries. -m u:<user>:r shares it with a user, -m g:<group>:r '
      + 'with a group, -m o::r with everyone (a public feed) and -m o::- makes it private again. '
      + '-x u:<user> or -x g:<group> withdraws that grant. A feed is named by id, by the feed_N a '
      + 'listing shows, by any path through /feeds/, or by /proc/jobs/feed_N. Given a feed and no '
      + 'entry, it asks which user to share it with.',
    options: [
      '-m u:<user>:r     Share with a user (the perms must include r)',
      '-m g:<group>:r    Share with a group',
      '-m o::r | o::-    Make the feed public, or private again (chmod o+r / o-r is the same)',
      '-x u:<user>       Stop sharing with a user',
      '-x g:<group>      Stop sharing with a group',
    ],
    examples: [
      'setfacl -m u:someone:r /home/me/feeds/feed_12',
      'setfacl -m g:grantlab:r feed_12 feed_13',
      'setfacl -m o::r feed_12                  # public',
      'setfacl -x u:someone feed_12',
      'setfacl feed_12                          # asks who to share it with',
    ],
  },
  getfacl: {
    usage: 'getfacl <path>...',
    summary: 'Show who can read a feed: users, groups, and whether it is public',
    description:
      'Show who can read a feed, in the familiar block: a # file: line, the owner\'s user:: entry, '
      + 'one user: line per user and one group: line per group holding access, then other:: '
      + '(r-- when the feed is public).',
    examples: [
      'getfacl /home/me/feeds/feed_12',
    ],
  },
  chmod: {
    usage: 'chmod o+r|o-r <feed>...',
    summary: 'Make a feed public, or private again',
    description: 'The other entry of a feed\'s access list spelled as a mode: o+r makes it public, o-r private, '
      + 'exactly as setfacl -m o::r and o::- do. No other mode is one a feed has.',
    examples: [
      'chmod o+r feed_12',
      'chmod o-r /proc/jobs/feed_12',
    ],
  },
  setfattr: {
    usage: 'setfattr -n tag -v <value> <path>... | setfattr -x tag [-v <value>] <path>...',
    summary: 'Hang a tag on a feed, or take it off',
    description:
      'A feed\'s tags are the values of one extended attribute, tag (also user.tag): CUBE\'s '
      + 'freeform labels. -n tag -v <value> hangs one of your tags (a folder under /proc/tags: '
      + 'mkdir /proc/tags/<name> makes a tag, and naming one that does not exist is an error); '
      + '-x tag -v <value> takes it off; -x tag alone takes every tag off, as '
      + 'setfattr removes the whole attribute. A feed is named by id, by feed_N, by any path '
      + 'through /feeds/, or by its projection /proc/jobs/feed_N. Silent on success.',
    options: [
      '-n, --name tag        The attribute to set (only tag exists)',
      '-v, --value <value>   The tag',
      '-x, --remove tag      Remove the tag given by -v, or every tag without -v',
    ],
    examples: [
      'setfattr -n tag -v urgent feed_12',
      'setfattr -n tag -v review feed_12 feed_13',
      'setfattr -x tag -v urgent /proc/jobs/feed_12',
    ],
  },
  getfattr: {
    usage: 'getfattr [-n tag] <path>...',
    summary: 'Show the tags a feed wears',
    description:
      'Show a feed\'s tags in getfattr\'s dump shape: a # file: line, then one tag="…" line per tag.',
    examples: [
      'getfattr feed_12',
      'getfattr -n tag /home/me/feeds/feed_12',
    ],
  },
  config: {
    usage: 'config write <cfs-path> <base64-content>',
    description: 'Write a small configuration document into the user\'s CUBE home (the durable layer: argus desktops, surface preferences). Reads travel the ordinary cat. Documents are notes, not datasets: 256KB limit.',
    options: [],
    examples: [
      'config write ~/.config/argus/desktops/quad.desk dmlldyBmaWxlcwo=   # a saved argus desktop',
      'cat ~/.config/argus/desktops/quad.desk                             # reading one back',
    ],
  },
  upload: {
    usage: 'upload <local_path_or_glob> <chris_path>',
    description: 'Upload local files, directories, or glob matches to ChRIS with progress tracking',
    options: [
      'Displays progress bar showing:',
      '  - File count and percentage complete',
      '  - Estimated time remaining (ETA)',
      '  - Data transfer progress',
      'Shows summary statistics after upload',
    ],
    examples: [
      'upload ~/data/file.csv /home/user/uploads/',
      'upload ~/Pictures/earthandmoon* .',
      'upload ./results/ ~/data/',
      'upload ~/experiment/data /home/user/projects/',
    ],
  },
  download: {
    usage: 'download <chris_path_or_glob> <local_path> [-f|--force]',
    description: 'Download a ChRIS file, directory, or CFS glob to the local filesystem with progress tracking',
    options: [
      '-f, --force   Overwrite existing local paths',
      'Progress bar shows files, ETA, bytes transferred',
    ],
    examples: [
      'download /home/user/data ./data',
      'download /home/user/results/*.nii ./results/',
      'download /feeds/feed_123 ./downloads -f',
    ],
  },
  connect: {
    usage: 'connect <username> <url> [password]',
    description: 'Connect to ChRIS server',
    examples: [
      'connect alice https://cube.chrisproject.org/api/v1/',
      'connect bob http://localhost:8000/api/v1/ mypassword',
    ],
  },
  logout: {
    usage: 'logout',
    description: 'Disconnect from ChRIS server',
    examples: ['logout'],
  },
  plugin: {
    usage: 'plugin <subcommand> [options]',
    description: 'Work with a single ChRIS plugin - run, search, view documentation',
    options: [
      '',
      'DESCRIPTION:',
      '  Plugins are computational units in ChRIS that process data. The "plugin"',
      '  command operates on individual plugins - running them, searching for specific',
      '  plugins, or viewing their documentation.',
      '',
      'SUBCOMMANDS:',
      '  run [--detach] <searchable> [params]  Run a plugin and wait for it to finish',
      '                               (--detach returns the instance id at once)',
      '  info <name>-v<version>       Show one plugin whole: facts and every parameter',
      '  search <searchable>          Resolve a searchable to plugin IDs',
      '  readme <pluginId>            Display plugin README documentation',
      '',
      'SEARCHABLE FORMATS:',
      '  Simple:     pl-dircopy',
      '  Compound:   name:pl-dircopy,version:1.3.2',
      '  ID-based:   id:42',
      '  Batch:      id:77++id:33  (multiple plugins)',
      '',
      'PLUGIN RUN PARAMETERS:',
      '  Plugin-specific parameters use CLI flag format:',
      '    --param value              Single parameter',
      '    --flag                     Boolean flag',
      '    --param1 val1 --param2 val2   Multiple parameters',
      '',
      '  Run "parametersofplugin <name>" to see available parameters for a plugin.',
    ],
    examples: [
      '# Read one plugin: the same manual "cat /bin/<entry>" prints',
      'plugin info pl-dircopy-v1.0.0',
      'plugin info pl-dircopy 1.0.0',
      '',
      '# Search for plugins',
      'plugin search pl-dircopy',
      'plugin search name:dcm2niix',
      'plugin search id:42',
      '',
      '# View plugin documentation',
      'plugin readme 42',
      'plugin readme pl-dircopy',
      '',
      '# Run a plugin (simple)',
      'plugin run pl-dircopy',
      '',
      '# Run plugin with parameters',
      'plugin run pl-dircopy --dir /incoming',
      'plugin run name:pl-dcm2niix,version:1.0.2 --outputdir /results',
      '',
      '# Run with multiple parameters',
      'plugin run pl-segmentation --threshold 0.5 --method watershed',
      '',
      '# Run with specific version',
      'plugin run name:pl-dircopy,version:2.1.1 --dir /data',
    ],
  },
  plugins: {
    usage: 'plugins <subcommand> [options]',
    description: 'Manage collections of ChRIS plugins - list, add, delete, query',
    options: [
      '',
      'DESCRIPTION:',
      '  Plugins are computational units in ChRIS. The "plugins" command operates on',
      '  collections of plugins - listing all available plugins, adding new plugins to',
      '  ChRIS, deleting plugins, or querying plugin metadata.',
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  add <input>       [admin] Register a new plugin to ChRIS',
      '  delete <id>       [admin] Remove a plugin from ChRIS',
      '  overview          Show plugin system overview',
      '',
      'PLUGINS ADD OPTIONS:',
      '  --compute <resources>         Comma-separated compute resources (default: host)',
      '  --store <url>                 Peer store URL (default: cube.chrisproject.org)',
      '  --adminUser <username>        Administrator username (non-interactive compatibility)',
      '  --adminPassword <password>    Administrator password (non-interactive compatibility)',
      '  --publicRepo <url>            Public repository URL for the plugin',
      '',
      'PLUGIN INPUT FORMATS:',
      '  Plugin name:      pl-dircopy',
      '  Docker image:     fnndsc/pl-dircopy:2.1.1',
      '  Store URL:        https://cube.chrisproject.org/api/v1/plugins/96/',
    ],
    examples: [
      '# List all plugins',
      'plugins list',
      'plugins list --all',
      'plugins list --search name:dircopy',
      'plugins list --fields name,version,dock_image',
      'plugins search dircopy',
      '',
      '# Inspect available fields',
      'plugins inspect',
      '',
      '# Delete a plugin',
      'plugins delete 42',
      '',
      '# Show plugin system overview',
      'plugins overview',
      '',
      '# Add plugin from peer store (searches cube.chrisproject.org)',
      'plugins add pl-dircopy',
      'plugins add pl-dircopy --compute host,gpu',
      '',
      '# Add a plugin with a temporary administrator identity',
      'sudo plugins add pl-dircopy',
      '',
      '# Add plugin from Docker image',
      'plugins add fnndsc/pl-dircopy:2.1.1',
      'plugins add fnndsc/pl-dircopy:2.1.1 --compute host',
      '',
      '# Add plugin from custom peer store',
      'plugins add pl-custom --store https://my-cube.org/api/v1/',
      '',
      '# Add plugin with specific repository',
      'plugins add my-plugin:latest --publicRepo https://github.com/org/my-plugin',
    ],
  },
  feed: {
    usage: 'feed <subcommand> [options]',
    description: 'Work with a single ChRIS feed - create, annotate, comment',
    options: [
      '',
      'SUBCOMMANDS:',
      '  create <path>                    Create a new feed from a data directory',
      '  note <feedId>                    Show the feed\'s note',
      '  note edit <feedId>               Edit the note in the surface\'s editor (edit /proc/jobs/feed_N/note)',
      '  note <feedId> --title <t>        Update note title',
      '  note <feedId> --content <c>      Update note content',
      '  comments <feedId>                List all comments on a feed',
      '  comment add <feedId>             Add a comment (--title, --content)',
      '  comment edit <feedId> <commentId>  Edit a comment (--title, --content)',
      '  comment delete <feedId> <commentId>  Delete a comment',
      '  rm [<feed>] [-f]                 Remove a feed and everything in it (asks first)',
      '  tree [<feed>]                     Render the feed\'s plugin-instance DAG',
      '  tree [<feed>] --focus <id>        Scope the tree to one node\'s subtree',
      '  tree [<feed>] --max-nodes <n>     Cap rendered nodes (0 = all)',
      '  diagram [<feed>]                  Shallow alias of feed tree',
      '  diagram --signalflow [<feed>]     Emit the DAG as SignalFlow YAML to stdout',
      '                                   (pipe it: feed diagram --signalflow 42 | signalflow -)',
      '',
      '  <feed> accepts an ID, feed_N directory name, exact title, or unique search.',
      '  Omit it while inside a feed_N path to use the current directory\'s feed.',
    ],
    examples: [
      'feed create /home/user/uploads/MRI-data',
      'feed tree 1669',
      'feed diagram                       # Current feed, from inside feed_N',
      'feed note 42',
      'feed note 42 --title "QC passed" --content "No artefacts found"',
      'feed comments 42',
      'feed comment add 42 --title "Issue" --content "Slice 14 looks odd"',
      'feed comment edit 42 7 --content "Resolved — motion artefact, excluded"',
      'feed comment delete 42 7',
    ],
  },
  feeds: {
    usage: 'feeds <subcommand> [options]',
    description: 'Manage collections of ChRIS feeds - list, delete, share, query',
    options: [
      '',
      'DESCRIPTION:',
      '  A feed represents a data analysis workflow in ChRIS - a DAG of linked plugin',
      '  instances, also navigable as a folder at /home/<user>/feeds/.',
      ...RESOURCE_LIST_OPTIONS,
      '--user <username>   Filter by owner username (admin only)',
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  delete <id>       Remove a feed',
    ],
    examples: [
      'feeds list',
      'feeds list --all',
      'feeds list --limit 100',
      'feeds search experiment',
      'feeds list --fields id,name,creation_date',
      'feeds list --user radstar',
      'feeds list --all --user radstar',
      'feeds inspect',
      'feeds delete 123',
    ],
  },
  files: {
    usage: 'files <subcommand> [path] [options]',
    description: 'Manage ChRIS file resources',
    options: [...RESOURCE_LIST_OPTIONS],
    examples: [
      'files list',
      'files list /path',
      'files search fname:dicom',
      'files inspect',
    ],
  },
  links: {
    usage: 'links <subcommand> [path] [options]',
    description: 'Manage ChRIS link resources',
    options: [...RESOURCE_LIST_OPTIONS],
    examples: ['links list', 'links search', 'links inspect'],
  },
  dirs: {
    usage: 'dirs <subcommand> [path] [options]',
    description: 'Manage ChRIS directory resources',
    options: [...RESOURCE_LIST_OPTIONS],
    examples: ['dirs list', 'dirs search', 'dirs inspect'],
  },
  pipeline: {
    usage: 'pipeline <subcommand> [args]',
    description: 'Manage and execute ChRIS pipelines (registered DAG workflows)',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  info <name|id>        Show pipeline nodes, plugins, and topology',
      '  manifest <name|id|slug>  Emit complete registered invocation YAML',
      '  run <name|id>         Run a pipeline on the context node and wait for it',
      '  source <name|id>      Display the pipeline YAML source file',
      '  diagram <name|id>     Draw the pipeline as a shallow tree',
      '    --withargs          Include stored non-null plugin defaults inline',
      '    --signalflow        Emit SignalFlow YAML instead of the shallow tree',
      '  delete <id>           Remove a pipeline',
      '',
      'RUN OPTIONS:',
      '  --detach              Return the instance ids at once, without waiting',
      '  --compute <resource>  Override compute resource for all nodes',
      '  --previous <inst_id>  Explicit previous instance ID (default: context node)',
      '  --paramFile <cfs-file> Apply one sparse YAML invocation overlay',
      '  --<node>.<parameter> <value>  Override one hosted plugin parameter',
      '  --<node>.<control> <value>    Override one node execution control',
      '  Use --@<piping-id>.<field> when a node title is ambiguous or shell-unsafe',
      '',
      'PIPELINE EXECUTABLES:',
      '  Pipelines also appear in /bin (colored magenta) and can be invoked directly.',
      '  <PipelineName>              Run pipeline on context node',
      '  <PipelineName> --nodes      Show DAG structure (alias: --parameters)',
      '  <PipelineName> --source     Show YAML source (alias: --readme)',
      '  <PipelineName> --manifest   Emit complete registered invocation YAML',
      '  <PipelineName> --diagram    Draw the shallow pipeline topology',
      '  <PipelineName> --signalflow Emit SignalFlow YAML directly',
      '    --withargs                Include arguments with --diagram',
      '  cat /bin/<PipelineName>     Show a fast cached executable summary',
    ],
    examples: [
      'pipeline list                          # List all pipelines',
      'pipeline list PHI                      # Filter by name',
      'pipeline info PHI_detection            # Show nodes and topology',
      'pipeline manifest PHI_detection        # Registered invocation YAML',
      'pipeline run PHI_detection             # Run on current context node',
      'pipeline run PHI_detection --compute gpu',
      'pipeline run PHI_detection --segmentation.threshold 0.5',
      'pipeline run PHI_detection --paramFile ~/params/run.yaml',
      'pipeline source PHI_detection          # Show YAML source',
      'pipeline diagram PHI_detection         # Draw the authored DAG',
      'pipeline diagram --withargs PHI_detection',
      'pipeline diagram --signalflow PHI_detection | signalflow -',
      '',
      '# Direct invocation from /bin',
      'PHI_detection                          # Run with defaults',
      'PHI_detection --nodes                  # Show node structure',
      'PHI_detection --source                 # Show YAML source',
      'PHI_detection --manifest               # Registered invocation YAML',
      'PHI_detection --diagram                # Draw the authored DAG',
      'PHI_detection --signalflow             # Emit SignalFlow YAML',
      'cat /bin/PHI_detection                 # Cached executable summary',
    ],
  },
  pacs: {
    usage: 'pacs <subcommand> [args]',
    description: 'PACS subsystem — server context, query, and series retrieval',
    options: [
      'SUBCOMMANDS:',
      '  connect               List registered PACS servers with active one marked',
      '  connect <name|id>     Set active PACS server',
      '  disconnect            Clear active PACS server',
      '  list                  List registered PACS servers (alias: pacs connect)',
      '  query <Key:Value...>  Create PACS query and wait for results',
      '  pull <vfs-path...>    Pull DICOM series into ChRIS storage',
      '  status <target>       Per-series pulled/pending report with in-CUBE paths;',
      '                        target is an expression, VFS path, or query id',
    ],
    examples: [
      'pacs                              # Show active server',
      'pacs connect                      # List all servers',
      'pacs connect PACSDCM              # Set active server by identifier',
      'pacs connect 1                    # Set active server by numeric ID',
      'pacs disconnect                   # Clear active server',
      'pacs list                         # List all servers',
      'pacs query PatientID:1234         # Query PACS',
      'pacs pull /net/pacs/queries/42_AccessionNumber:12345678',
      'pacs status AccessionNumber:22119730   # What has landed in CUBE, what is missing',
    ],
  },
  'pacs query': {
    usage: 'pacs query <Key:Value[,Key:Value...]> [--table | --csv | --csv-to <cfs-path>] [--series] [--title <title>] [--pacsserver <id>] [--fresh]',
    description: 'Create a PACS query, wait for results, and print the VFS path',
    options: [
      '--title <title>      Title for the query record (default: Query <timestamp>)',
      '--pacsserver <id>    Override PACS server (default: context PACSserver);',
      '                     a comma-separated list asks each and names the server on every row',
      '--patients <list>    Ask after several patients: MRNs comma-separated, or @<cfs-file>',
      '                     (one MRN per line; blanks and # comments ignored)',
      '--csv                Render the answer as CSV (a row per study, and one per patient with none)',
      '--csv-to <cfs-path>  Write that CSV into ChRIS storage, where a detached surface can reach it',
      '                     (given no path, the destination is asked for)',
      '--force              Overwrite the table at that path; without it, an existing file is kept',
      '--table              Show the answer\'s rows as an aligned table: the CSV\'s columns, for a screen',
      '--series             One row per series instead of per study (on the table and in the CSV);',
      '                     alone, it shows the series table',
      '--anon               Stand in for names and record numbers (for demonstrating on a live PACS)',
      '--fresh              Ask the PACS even if this question was answered before',
      '--help               Show this help',
    ],
    examples: [
      'pacs query PatientID:1234',
      'pacs query PatientID:1234 --fresh      # ignore the stored answer',
      'pacs query AccessionNumber:12345678 --title "Hip DDH workup"',
      'pacs query PatientID:1234,StudyDate:20240101',
      'pacs query PatientID:1234 --table      # the rows, aligned, one per study',
      'pacs query PatientID:1234 --series     # one row per series',
      'pacs query PatientID:1234 --csv-to ~/audit.csv --table --series',
      '',
      '# Standalone alias (identical behaviour)',
      'query PatientID:1234',
    ],
  },
  'pacs pull': {
    usage: 'pacs pull [--nowait] [--retry N] [--new-feed <title> [--plugin <selector>|--pipeline <selector>] [-- <args...>]] <vfs-path|query-expr> [...]',
    description: 'Pull PACS series into ChRIS storage (blocking, with LONK progress)',
    options: [
      '--detach      Fire retrieves and return the handles at once; prints <seriesUID> <retrieveId> per line',
      '              (--nowait is the older spelling of the same flag)',
      '--retry N     Re-fire retrieves for [NO LONK] series up to N additional times',
      '--new-feed <title>  Create one named feed from the complete retrieved selection',
      '--plugin <selector> Attach one plugin to the new Feed root',
      '--pipeline <selector> Attach one pipeline to the new Feed root',
      '-- <args...>        Forward remaining tokens to the selected analysis',
      '                    (cannot be combined with --detach)',
      '--help        Show this help',
    ],
    examples: [
      'pacs pull /net/pacs/queries/42_AccessionNumber:12345678',
      'pacs pull /net/pacs/queries/42_.../Study_1.2.3_US-Hips_DDH',
      'pacs pull AccessionNumber:12345678   # query-then-pull shorthand',
      'pacs pull AccessionNumber:12345678 --new-feed "Brain MRI"',
      '',
      '# Standalone alias (identical behaviour)',
      'pull /net/pacs/queries/42_AccessionNumber:12345678',
    ],
  },
  'pacs connect': {
    usage: 'pacs connect [<name|id>]',
    description: 'List registered PACS servers or set the active one',
    examples: [
      'pacs connect                  # List all servers with active marked',
      'pacs connect PACSDCM          # Set active server by identifier',
      'pacs connect 1                # Set active server by numeric ID',
    ],
  },
  'pacs disconnect': {
    usage: 'pacs disconnect',
    description: 'Clear the active PACS server from context',
    examples: [
      'pacs disconnect               # Clear active server',
    ],
  },
  'pacs list': {
    usage: 'pacs list',
    description: 'List registered PACS servers with active one marked (alias: pacs connect)',
    examples: [
      'pacs list                     # List all servers',
    ],
  },
  pacsservers: {
    usage: 'pacsservers <subcommand> [options]',
    description: 'List or inspect available PACS servers (context-aware)',
    examples: [
      'pacsservers list         # List PACS servers',
      'pacsservers list --table # Table view',
      'pacsservers fieldslist   # Show fields',
    ],
  },
  pacsqueries: {
    usage: 'pacsqueries <subcommand> [options]',
    description: 'Create or list PACS queries (uses current pacsserver context unless overridden)',
    options: [
      '--pacsserver <id|name>  Use specific PACS server for this call',
      '--title <string>        Title for created query',
      '--search <filters>      Filters for list (supports comma-separated key:value)',
    ],
    examples: [
      'pacsqueries list                          # List for current pacsserver',
      'pacsqueries list --pacsserver PACSDCM     # Override server',
      'pacsqueries create "PatientID:1234" --title "PID 1234"',
      'pacsqueries decode <id>                   # Decode a query result',
    ],
  },
  pacsretrieve: {
    usage: 'pacsretrieve <subcommand> [options]',
    description: 'Pull or inspect DICOM retrieves for PACS queries',
    examples: [
      'pacsretrieve pull <queryId>       # Pull data for a query',
      'pacsretrieve report <queryId>     # Show retrieve status',
      'pacsretrieve cancel <retrieveId> # Cancel a retrieve',
    ],
  },
  context: {
    usage: 'context',
    description: 'Display current ChRIS context information',
    examples: ['context'],
  },
  whoami: {
    usage: 'whoami',
    description: 'Print the currently authenticated ChRIS username',
    examples: ['whoami'],
  },
  id: {
    usage: 'id',
    description: 'Print the current CUBE user as a Unix-style UID, projected primary GID, and complete list of CUBE group memberships.',
    examples: ['id'],
  },
  ping: {
    usage: 'ping [-c N] [cube]',
    summary: 'Round trips to CUBE, timed',
    description: 'Makes N (3) HTTP round trips to the CUBE this session talks to and times each, then sums up as ping does — and adds the average of this session\'s own calls to CUBE so far. Only CUBE is pinged from here: a hosted session is not a probe for the network it sits on.',
    options: ['  -c N    Round trips to make (default 3, at most 20)'],
    examples: ['ping', 'ping -c 10'],
  },
  chrisfetch: {
    usage: 'chrisfetch',
    summary: 'The brain beside the session\'s facts, neofetch style',
    description: 'Who you are and where, feeds by scope, jobs run and the failure rate, the index\'s state, the surfaces attached, the uptime — beside the ChRIS brain. All from what the session already holds: no extra calls.',
    examples: ['chrisfetch', 'chrisfetch | lolcat'],
  },
  file: {
    usage: 'file <path>...',
    summary: 'What a file is, by its first bytes',
    description: 'Reads a CFS file\'s head and names it by its magic: DICOM, NIfTI, gzip, PNG, JPEG, PDF, ZIP, JSON, text and more, with its size.',
    examples: ['file 0001.dcm', 'file ~/data/*'],
  },
  xxd: {
    usage: 'xxd [-s OFFSET] [-l LENGTH] <path>',
    summary: 'A hex dump of a file',
    description: 'The canonical hex dump — offset, sixteen bytes in pairs, the text beside — of a CFS file. 256 bytes unless -l asks for more; -s starts further in. Says how much of the file it showed.',
    options: ['  -s OFFSET   Start at this byte (default 0)', '  -l LENGTH   Show this many bytes (default 256)'],
    examples: ['xxd 0001.dcm', 'xxd -s 128 -l 16 0001.dcm', 'xxd -l 4096 image.nii'],
  },
  strings: {
    usage: 'strings [-n MIN] [-l LIMIT] <path>',
    summary: 'The readable runs in a file',
    description: 'Prints the runs of printable characters, MIN (4) or longer, in a CFS file — the way to see what a binary carries. 200 lines unless -l asks for more; says how many there were.',
    options: ['  -n MIN      Shortest run to show (default 4)', '  -l LIMIT    Most runs to show (default 200)'],
    examples: ['strings 0001.dcm', 'strings -n 8 report.pdf'],
  },
  sha256sum: {
    usage: 'sha256sum <path>...',
    summary: 'The SHA-256 digest of a file',
    description: 'Prints each CFS file\'s SHA-256 as hex, then its name, in the format the coreutils tool uses.',
    examples: ['sha256sum image.nii.gz', 'sha256sum ~/uploads/*'],
  },
  md5sum: {
    usage: 'md5sum <path>...',
    summary: 'The MD5 digest of a file',
    description: 'Prints each CFS file\'s MD5 as hex, then its name.',
    examples: ['md5sum image.nii.gz'],
  },
  motd: {
    usage: 'motd [surface]',
    summary: 'The greeting a session gives on arrival',
    description: 'Says who you are, how many feeds you hold, how many jobs have run and what share of them failed, and what is running now — from the session\'s own index, at no cost. While the index is still warming it says what it holds so far. A surface may name itself (motd ARGUS) and the greeting says where you arrived. Ends with a short fortune.',
    examples: ['motd', 'motd ARGUS'],
  },
  whereami: {
    usage: 'whereami',
    description: 'Print the current CUBE URL',
    examples: ['whereami'],
  },
  proc: {
    usage: 'proc <jobs|stat|feeds|refresh|retry|find|here|watch|unwatch> [args]',
    summary: 'Job history inspector — navigate, query and monitor ChRIS pipeline execution via /proc/jobs',
    description: '/proc/jobs is a job history inspector for every computation visible to the current ChRIS identity. Each plugin instance is a discrete job with a parent, zero or more children, a status, parameters, and a log. Jobs are grouped into feeds (pipeline runs), and the parent-child relationships form a DAG: the execution tree of a full computation. /proc/jobs exposes this as a navigable filesystem. The daemon restores an identity-scoped local topology checkpoint, validates feed visibility with CUBE, and reconciles all plugin instances in the background. Restored queries remain usable while syncing; a cold cache still guards global queries until complete. CUBE remains authoritative.',
    subcommands: [
      'jobs list                               List all feeds with full counter fields (default 20)',
      'jobs list --fields id,title,erroredJobs Select columns',
      'jobs list --sort erroredJobs --reverse  Sort by field',
      'jobs list --table                       Tabular output',
      'jobs list --csv                         CSV output',
      'jobs list --all                         All feeds (no limit)',
      'jobs list --search failed               Filter by title substring',
      'jobs list --force                       Wait for warm-up, then list complete results',
      'jobs inspect                            Show all available field names',
      'stat                                   Show cache summary',
      'stat <feed_id>                         Show raw counters + topology state for one feed',
      'feeds <title> [--force]                Search feed titles; --force waits for warm-up',
      'universe                               Every feed the index holds as it landed: size, status, pipeline shape; honest while warming',
      'layout <name>                          Where a surface last laid the universe out under a layout, as the session keeps it',
      'layout put <name> <places>             Keep a layout: node ids to [x, y, z], as JSON (surfaces put what they settle)',
      'refresh                                Rebuild entire proc cache',
      'refresh <feed_id>                      Rebuild cache for one feed only',
      'retry                                  Resume a failed topology sweep at its failed page',
      'find <id>                              Targeted instance lookup; available during warm-up',
      'find <name> [--force]                  Name search; --force waits for warm-up',
      'here                                   Navigate from a CFS feed/output path to its matching job',
      'watch <feed>                           Keep a running feed live: sample it while it runs, push its DAG to every surface',
      'watch                                  List the session\'s watches with their state',
      'unwatch <feed>                         Release the watch on a feed',
    ],
    examples: [
      'proc jobs list',
      'proc jobs list --sort erroredJobs --reverse --table',
      'proc jobs list --fields id,title,erroredJobs,startedJobs --all',
      'proc jobs list --search failed',
      'proc jobs inspect',
      'proc stat',
      'proc stat 899',
      'proc feeds failed',
      'proc universe',
      'proc refresh',
      'proc retry',
      'proc find 64306',
      'proc find pl-fshack',
      'proc here',
      'proc watch feed_2583',
      'proc unwatch 2583',
    ],
  },
  physicalmode: {
    usage: 'physicalmode [on|off]',
    description: 'Toggle or display physical filesystem mode',
    options: [
      'on          Enable physical mode (paths used directly)',
      'off         Disable physical mode (use logical-to-physical mapping)',
    ],
    examples: [
      'physicalmode          # Show current status',
      'physicalmode on       # Enable physical mode',
      'physicalmode off      # Disable physical mode',
    ],
  },
  parametersofplugin: {
    usage: 'parametersofplugin <plugin_name>',
    description: 'Display parameters for a specific plugin',
    examples: [
      'parametersofplugin pl-dircopy',
      'parametersofplugin pl-simpledsapp',
    ],
  },
  tree: {
    usage: 'tree [options] [path]',
    description: 'Display directory tree structure',
    options: [
      '--follow    Follow symbolic links when traversing',
      '--path      Emit one full path per entry (grep-friendly, no tree art)',
      '--dirs      Show directories only',
      '--dirpath   Emit one full directory path per line',
    ],
    examples: [
      'tree                  # Tree of current directory',
      'tree /home/user/data  # Tree of specific path',
      'tree --follow         # Follow symbolic links',
      'tree --path           # One path per line, no decoration',
      'tree --dirs           # Directory hierarchy only',
      'tree --dirpath        # One directory path per line',
    ],
  },
  du: {
    usage: 'du [options] [path]',
    description: 'Display disk usage statistics (mimics Linux du)',
    options: [
      '-h, --human-readable  Print sizes in human readable format',
      '-s, --summarize       Display only total for each argument',
      '-a, --all             Show counts for all files, not just directories',
      '-c, --total           Produce a grand total',
      '-d N, --max-depth=N   Print total only if N or fewer levels below',
      '-S, --separate-dirs   Do not include size of subdirectories',
    ],
    examples: [
      'du                    # Disk usage of current directory',
      'du -h                 # Human-readable sizes (1K, 234M, 2G)',
      'du -s /home/user/data # Summary only for specified path',
      'du -a                 # Show all files, not just directories',
      'du -c                 # Show grand total at end',
      'du -d 2               # Max depth of 2 levels',
      'du -sh                # Human-readable summary',
    ],
  },
  store: {
    usage: 'store <subcommand> [options]',
    description: 'Browse, search, and install plugins from ChRIS peer store',
    options: [
      '',
      'NOTE: The Store is an external peer ChRIS instance, not a local CUBE resource.',
      '      Standard resource options (--all, --limit, etc.) do not apply.',
      '',
      'SUBCOMMANDS:',
      '  list              Browse all plugins in the peer store',
      '  search <query>    Search plugins by name',
      '  install <name>    Install a plugin from the store into local CUBE',
      '  inspect           Show current peer store URL and connection info',
      '  set <url>         Set peer store URL (persisted to ~/.config/chell/settings.json)',
      '  reset             Reset peer store URL to default (cube.chrisproject.org)',
      '',
      'INSTALL OPTIONS:',
      '  --compute <names>     Compute resources (comma-separated)',
      '  Use `sudo store install …` for an administrator installation.',
      '-l                      Long listing format',
    ],
    examples: [
      'store list',
      'store search dicom',
      'store install pl-dcm2niix',
      'store install pl-dcm2niix-v1.2.3',
      'store install fnndsc/pl-dcm2niix:1.2.3',
      'store install pl-dcm2niix --compute moc',
      'store inspect',
      'store set https://my-cube.org/api/v1/',
      'store reset',
    ],
  },
  compute: {
    usage: 'compute <subcommand> [options]',
    description: 'Manage ChRIS compute resources',
    options: [
      ...RESOURCE_LIST_OPTIONS,
    ],
    examples: [
      'compute list',
      'compute list --table',
      'compute list --csv',
      'compute inspect',
    ],
  },
  tag: {
    usage: 'tags <subcommand> [options]',
    description: 'Manage ChRIS tags',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  create <name>     Create a new tag',
      '  update <id> <name>  Rename a tag',
      '  delete <id>       Remove a tag',
    ],
    examples: ['tags list', 'tags search brain', 'tags inspect', 'tag create neuro', 'tag delete 5'],
  },
  tags: {
    usage: 'tags <subcommand> [options]',
    description: 'Manage ChRIS tags',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  create <name>     Create a new tag',
      '  update <id> <name>  Rename a tag',
      '  delete <id>       Remove a tag',
    ],
    examples: ['tags list', 'tags search brain', 'tags inspect', 'tag create neuro', 'tag delete 5'],
  },
  record: {
    usage: 'record <start <manifest>|stop|status>',
    description: 'Write what this session does down as a manifest',
    options: [
      'SUBCOMMANDS:',
      '  start <manifest>  Begin capturing the lines this session runs',
      '  stop              Write the manifest and say what it holds',
      '  status            Whether anything is recording, and how much (the default)',
      '',
      'A recording captures typed lines and the lines a surface mints from a press',
      'alike. It never invents expectations: adding `expect` lines is the author\'s',
      'act, and the one that turns a recording into a test. Identifiers a PACS line',
      'wears on its face (PatientID, AccessionNumber, PatientName) are offered as',
      'parameters, so the file is shareable rather than personal.',
    ],
    examples: [
      'record start ~/flows/sag-cohort.mise',
      '# … do the work, by hand or by pressing …',
      'record stop',
      'play ~/flows/sag-cohort.mise --param MRN=1234567',
    ],
  },
  play: {
    usage: 'play <manifest> [--param NAME=value]... [--pace <duration>] [--dry-run]',
    description: "Run a workflow manifest: the lines an operator could have typed",
    options: [
      'OPTIONS:',
      '  --param NAME=value   Supply a parameter the manifest declares (repeatable)',
      '  --pace <duration>    Wait between lines, for watching a play at a surface',
      '  --dry-run            Expand the lines and show them without running any',
      '',
      'A MANIFEST:',
      '  # a comment',
      '  @name         what this workflow is',
      '  @description  one line about it',
      '  @param        MRN            a parameter it needs',
      '  @param        LABEL = draft  one with a default',
      '  <any kernel line>',
      '',
      'PRONOUNS a line may use:',
      '  ${gather}        every gathered member, as operands (where it was gathered FROM)',
      '  ${gather.place}  the same members, where they LANDED in CUBE',
      '  ${gather.first}  ${gather.last}  ${gather.3}  ${gather.size}  ${gather.name}',
      '  ${gather.first.place}  one member, where it landed (pull takes the address, image takes the place)',
      '  ${feed}          the feed this session most recently worked in',
      '  ${run}           the run it most recently scheduled',
      '  ${run.place}     where that run writes — what the next act in a chain takes',
      '  ${query}         where its most recent PACS answer lives',
      '  ${cwd}           where the session is standing',
    ],
    examples: [
      'play ~/flows/sag-cohort.mise --param MRN=1234567',
      'play ~/flows/sag-cohort.mise --dry-run',
      'play ~/flows/battery.mise --pace 2s',
    ],
  },
  expect: {
    usage: 'expect <gather|feed|run|path> [<target>] <property> [<predicate> <value>] [--within <duration>]',
    description: 'State a claim about the session, and refuse when it does not hold',
    options: [
      'SUBJECTS:',
      '  gather size|pulled|name          The cohort this session is working on',
      '  feed <id> status                 A feed, as this session indexed it',
      '  run <instance-id> status         One plugin instance',
      '  path <p> exists                  Whether a path is there',
      '  path <p> count [--matching <glob>]  How many things a folder holds',
      '  path <p> tags <TagName>          What a DICOM header says',
      '',
      'COMPARISONS:',
      '  eq  ne  gt  gte  lt  lte  contains  notContains  matches',
      '',
      'OPTIONS:',
      '  --within <duration>   Keep asking until the claim holds or the time is up (30s, 20m, 2h)',
      '  --matching <glob>     Narrow a count to names matching a shell pattern',
      '  --deep                Count beneath the folder too — a plugin files its output in a tree',
    ],
    examples: [
      'expect gather size eq 14',
      'expect run 601152 status eq finishedSuccessfully --within 20m',
      'expect path ~/feeds/feed_4599/pl-dcm2niix_1/data count --matching "*.nii*" gt 0',
      'expect path ~/anon tags PatientID eq anon-001',
    ],
  },
  gather: {
    usage: 'gather <subcommand> [path...]',
    description: "Hold the set of things this session is working on",
    options: [
      'SUBCOMMANDS:',
      '  list                     Show the cohort (the default)',
      '  add <path...>            Take series, directories or files into it',
      '  remove <path|index...>   Drop members, by path or by listed index',
      '  clear                    Empty it, name and feed included',
      '  name [<name>]            Read the cohort\'s name, or give it one',
    ],
    examples: [
      'gather',
      'gather add /net/pacs/queries/qid:3125/Study_1.2.3/Series_4.5.6',
      'gather add ~/uploads/brain',
      'gather remove 2',
      'gather name "sag cohort"',
    ],
  },
  group: {
    usage: 'groups <subcommand> [options]',
    description: 'Manage ChRIS user groups',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  inspect [<group>]             Show group identity, or fields when omitted',
      '  members <group>               List users in a group',
      '  create <name>                  [admin] Create a new group',
      '  delete <id>                    [admin] Remove a group',
      '  adduser <group> <user...>     [admin] Add one or more users',
      '  removeuser <group> <user...>  [admin] Remove one or more users',
    ],
    examples: ['groups list', 'group members pacs_users', 'group adduser pacs_users peter.hong joe.schmo', 'group removeuser pacs_users joe.schmo'],
  },
  groups: {
    usage: 'groups <subcommand> [options]',
    description: 'Manage ChRIS user groups',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  inspect [<group>]             Show group identity, or fields when omitted',
      '  members <group>               List users in a group',
      '  create <name>                  [admin] Create a new group',
      '  delete <id>                    [admin] Remove a group',
      '  adduser <group> <user...>     [admin] Add one or more users',
      '  removeuser <group> <user...>  [admin] Remove one or more users',
    ],
    examples: ['groups list', 'group members pacs_users', 'group adduser pacs_users peter.hong joe.schmo', 'group removeuser pacs_users joe.schmo'],
  },
  pluginmeta: {
    usage: 'pluginmetas <subcommand> [options]',
    description: 'Browse ChRIS plugin metadata (abstract tool identities across versions)',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  plugins <id>      List all registered versions of a plugin meta',
    ],
    examples: ['pluginmetas list', 'pluginmetas search dircopy', 'pluginmetas inspect', 'pluginmeta plugins 12'],
  },
  pluginmetas: {
    usage: 'pluginmetas <subcommand> [options]',
    description: 'Browse ChRIS plugin metadata (abstract tool identities across versions)',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  plugins <id>      List all registered versions of a plugin meta',
    ],
    examples: ['pluginmetas list', 'pluginmetas search dircopy', 'pluginmetas inspect', 'pluginmeta plugins 12'],
  },
  plugininstance: {
    usage: 'plugininstances <subcommand> [options]',
    description: 'Manage ChRIS plugin instances (jobs)',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  cancel <id>       Cancel a running job',
      '  delete <id>       Remove a job',
      '  output <id>       Show output folder path',
      '  parameters <id>   List job parameters',
    ],
    examples: ['jobs list', 'jobs list --all', 'jobs search status:started', 'jobs inspect', 'job cancel 42', 'job output 42'],
  },
  plugininstances: {
    usage: 'plugininstances <subcommand> [options]',
    description: 'Manage ChRIS plugin instances (jobs)',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  cancel <id>       Cancel a running job',
      '  delete <id>       Remove a job',
      '  output <id>       Show output folder path',
      '  parameters <id>   List job parameters',
    ],
    examples: ['jobs list', 'jobs list --all', 'jobs search status:started', 'jobs inspect', 'job cancel 42', 'job output 42'],
  },
  workflow: {
    usage: 'workflows <subcommand> [options]',
    description: 'Manage ChRIS workflows (pipeline executions)',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  run               Run a pipeline (alias: pipeline run)',
      '  jobs <id>         List plugin instances created by this workflow',
      '  rename <id> <title>  Rename a workflow',
      '  delete <id>       Remove a workflow',
    ],
    examples: ['workflows list', 'workflows list --all', 'workflows inspect', 'workflow jobs 7', 'workflow delete 7'],
  },
  workflows: {
    usage: 'workflows <subcommand> [options]',
    description: 'Manage ChRIS workflows (pipeline executions)',
    options: [
      ...RESOURCE_LIST_OPTIONS,
      '',
      'RESOURCE-SPECIFIC SUBCOMMANDS:',
      '  run               Run a pipeline (alias: pipeline run)',
      '  jobs <id>         List plugin instances created by this workflow',
      '  rename <id> <title>  Rename a workflow',
      '  delete <id>       Remove a workflow',
    ],
    examples: ['workflows list', 'workflows list --all', 'workflows inspect', 'workflow jobs 7', 'workflow delete 7'],
  },
  meta: { usage: 'pluginmetas <subcommand> [options]', description: 'Alias for pluginmeta/pluginmetas', options: [...RESOURCE_LIST_OPTIONS], examples: ['metas list', 'meta inspect'] },
  metas: { usage: 'pluginmetas <subcommand> [options]', description: 'Alias for pluginmeta/pluginmetas', options: [...RESOURCE_LIST_OPTIONS], examples: ['metas list', 'meta inspect'] },
  instance: { usage: 'plugininstances <subcommand> [options]', description: 'Alias for plugininstance/plugininstances/job/jobs', options: [...RESOURCE_LIST_OPTIONS], examples: ['instances list', 'instance cancel 42'] },
  instances: { usage: 'plugininstances <subcommand> [options]', description: 'Alias for plugininstance/plugininstances/job/jobs', options: [...RESOURCE_LIST_OPTIONS], examples: ['instances list', 'instance cancel 42'] },
  job: { usage: 'plugininstances <subcommand> [options]', description: 'Alias for plugininstance/plugininstances', options: [...RESOURCE_LIST_OPTIONS], examples: ['jobs list', 'job cancel 42', 'job output 42'] },
  jobs: { usage: 'plugininstances <subcommand> [options]', description: 'Alias for plugininstance/plugininstances', options: [...RESOURCE_LIST_OPTIONS], examples: ['jobs list', 'job cancel 42', 'job output 42'] },
  dcm: {
    usage: 'dcm <series|tags> <path> [options]',
    summary: 'DICOM as the kernel sees it: a folder as a series, a file or folder as tags',
    description: 'Read DICOM without leaving the session. `dcm series` answers what a folder is as a series: '
      + 'identity, modality, instance count, stack order, geometry, transfer syntax, bytes, and any '
      + 'annotations saved for its UID. `dcm tags` lists every element of a file, or what a folder\'s '
      + 'files share against what changes across them. Identifying tags are marked PHI and shown; '
      + 'a shared surface redacts them by that mark.',
    options: [
      'SUBCOMMANDS:',
      '  series <folder>                 The folder as a series (one header read, order from file names)',
      '  tags <file|folder>              Every tag of a file; constant versus varying across a folder',
      '',
      'OPTIONS (tags):',
      '  --all                           Show meta and private groups too',
      '  --filter <text>                 Only tags whose tag, name, value or decoding contains <text>',
      '',
      'A folder\'s tags are read from every file up to 512, then from an even sample; the listing says '
      + 'how many were read of how many there are.',
    ],
    examples: [
      'dcm series .                                  # This folder as a series',
      'dcm series /SERVICES/PACS/PACSDCM/patient/study/00005-T1-abcdef0',
      'dcm tags 0001-1.2.840.113619.2.55.3.1.dcm      # One file, grouped by module',
      'dcm tags . --filter Position                   # Position tags across the folder',
      'dcm tags . --all                               # Meta and private groups included',
    ],
  },
  image: {
    usage: 'image [--force] <path>',
    summary: 'Show a DICOM series or a volume — a browser draws it, a terminal reflects it',
    description: 'Open an image as the kernel sees it. `image <path>` resolves what the path is — a series '
      + 'folder, a `.dcm` file (its folder is the series), or a NIfTI/MGZ volume — and emits an image.view '
      + 'intent every attached surface renders in its own way: a graphical surface (ARGUS) opens a rendered '
      + 'pane; a text surface (a shared TTY) prints a reflection — the same facts `dcm series` shows, under an '
      + '`image` line, with a small ASCII or truecolour thumbnail of the middle slice. So the same `image` line '
      + 'works from a browser and from a terminal sharing one CALYPSO session.',
    options: [
      'OPTIONS:',
      '  --force                         Ride through the volume-size guard a graphical surface would hold at',
    ],
    examples: [
      'image ~/uploads/sag-anon                      # A series folder',
      'image /SERVICES/PACS/PACSDCM/patient/study/00005-T1-abcdef0',
      'image scan.dcm                                # A single file; its folder is the series',
      'image brain.nii.gz --force                    # A volume, past the size guard',
    ],
  },
  cubepath: {
    usage: 'cubepath <vfs-path> [--pacsserver <id>]',
    description: 'Show CUBE FS path and file count for each series under a PACS VFS path. Zero files = not pulled.',
    options: [
      '--pacsserver <id>    Override PACS server (default: context PACSserver)',
      '--help               Show this help',
    ],
    examples: [
      '# All series under a query',
      'cubepath /net/pacs/queries/AccessionNumber:12345678_qid:2661',
      '',
      '# All series under a study',
      'cubepath /net/pacs/queries/AccessionNumber:12345678_qid:2661/Study_1.2.3_Brain_MRI',
      '',
      '# Single series',
      'cubepath /net/pacs/queries/AccessionNumber:12345678_qid:2661/Study_1.2.3/Series_1.2.3.4_AX_T2',
    ],
  },
  query: {
    usage: 'query <Key:Value[,Key:Value...]> [--patients <list|@cfs-file>] [--title <title>] [--pacsserver <id>] [--fresh]',
    description: 'Create a PACS query, wait for results, and print the VFS path',
    options: [
      '--title <title>      Title for the query record (default: Query <timestamp>)',
      '--pacsserver <id>    Override PACS server (default: context PACSserver)',
      '--table              Render results as a table instead of the default list',
      '--fresh              Ask the PACS even if this question was answered before',
      '--help               Show this help',
    ],
    examples: [
      'query PatientID:1234',
      'query PatientID:1234 --fresh           # ignore the stored answer',
      'query AccessionNumber:12345678 --title "Hip DDH workup"',
      'query PatientID:1234,StudyDate:20240101',
      '',
      '# A PACS matches one patient at a time, so several MRNs is several queries',
      'query PatientID:1234,4532,6654         # three questions, one table',
      'query --patients @~/cohorts/ddh.txt    # a cohort from a file in ChRIS',
      'query StudyDate:20240101 --patients 1234,4532   # narrowed, per patient',
      'query PatientID:1234 --pacsserver PACSDCM,ORTHANC   # ask both, one listing',
      '',
      '# A cohort audit, as a table a spreadsheet reads',
      'query --patients @~/cohorts/ddh.txt --csv > audit.csv    # a local terminal',
      'query --patients @~/cohorts/ddh.txt --csv-to ~/audits/ddh.csv   # any surface',
      '',
      '# Use output path directly with pull',
      'pull $(query PatientID:1234 | grep "VFS path" | awk \'{print $3}\')',
    ],
  },
  pull: {
    usage: 'pull [--detach] [--retry N] [--new-feed <title> [--plugin <selector>|--pipeline <selector>] [-- <args...>]] <vfs-path|query-expr> [...]',
    description: 'Pull PACS series into ChRIS storage; accepts VFS paths or query expressions (blocking)',
    options: [
      '--detach      Fire retrieves and return the handles at once; prints <seriesUID> <retrieveId> per line',
      '              (--nowait is the older spelling of the same flag)',
      '--retry N     Re-fire retrieves for [NO LONK] series up to N additional times',
      '--new-feed <title>  Create one named feed from the complete retrieved selection',
      '--plugin <selector> Attach one plugin to the new Feed root',
      '--pipeline <selector> Attach one pipeline to the new Feed root',
      '-- <args...>        Forward remaining tokens to the selected analysis',
      '                    (cannot be combined with --detach)',
      '--help        Show this help',
    ],
    examples: [
      '# Pull all series in a query (blocking)',
      'pull /net/pacs/queries/42_AccessionNumber:12345678',
      '',
      '# Pull a single study',
      'pull /net/pacs/queries/42_AccessionNumber:12345678/Study_1.2.3_US-Hips_DDH',
      '',
      '# Pull a specific series',
      'pull /net/pacs/queries/42_AccessionNumber:12345678/Study_1.2.3_US-Hips_DDH/Series_1.2.3.4_XR',
      '',
      '# Pull multiple paths in one blocking call',
      'pull /net/pacs/queries/42_AccessionNumber:12345678 /net/pacs/queries/43_PatientID:P001',
      '',
      '# Pull directly from a query expression (creates query, waits, then pulls)',
      'pull PatientID:1234',
      'pull AccessionNumber:12345678',
      'pull AccessionNumber:12345678 --new-feed "Brain MRI"',
      '',
      '# Detached: take the handles and carry on',
      'pull --detach /net/pacs/queries/42_AccessionNumber:12345678',
      '# Output: <seriesUID> <retrieveId>  (one per series, in tree-walk order)',
    ],
  },
};
