/**
 * @file The keys reference, generated from the one chord table.
 *
 * `DRAWER_CHORDS` in apps/argus/src/console/argusLang.ts is the single source
 * of the prefix chords: the host reads it for the keys and the capsule
 * titles, the console for `argus keys`, the HELP pane for its rows. This
 * script renders the same table as apps/argus/docs/keys.adoc, so the
 * written reference cannot drift from the code (aegis.adoc:
 * keys-are-documented-from-one-table). `--check` compares instead of writing.
 *
 * Usage: node scripts/keys-doc.mjs [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';

const SOURCE = 'apps/argus/src/console/argusLang.ts';
const TARGET = 'apps/argus/docs/keys.adoc';
/** The compositions' language extensions, whose chords join the table. */
const EXTENSIONS = ['apps/argus/src/compositions/chris/lang.ts'];

/** Reads the chord table out of the source, entry by entry. */
export function chords_read(text) {
  const start = text.indexOf('export const DRAWER_CHORDS');
  const end = text.indexOf('];', start);
  if (start < 0 || end < 0) throw new Error(`${SOURCE}: DRAWER_CHORDS not found`);
  const block = text.slice(start, end);
  const chords = [];
  for (const m of block.matchAll(/\{ key: '((?:[^'\\]|\\.)+)', topic: '([a-z]+)', selector: (?:'[^']*'|null|splitSelector_of\('[a-z]+'\)), does: '((?:[^'\\]|\\.)+)'(?:, move: true)? \}/g)) {
    chords.push({ key: m[1].replace(/\\'/g, "'"), topic: m[2], does: m[3].replace(/\\'/g, "'") });
  }
  if (chords.length === 0) throw new Error(`${SOURCE}: no chord entries parsed`);
  // A composition's chords, each after the chord it names, as language_extend places them.
  for (const extensionPath of EXTENSIONS) {
    let extension = '';
    try { extension = readFileSync(extensionPath, 'utf8'); } catch { continue; }
    const placed = new Map();
    for (const m of extension.matchAll(/\{ after: '((?:[^'\\]|\\.)+)', key: '((?:[^'\\]|\\.)+)', topic: '([a-z]+)', selector: (?:'[^']*'|null), does: '((?:[^'\\]|\\.)+)'(?:, move: true)? \}/g)) {
      const after = m[1].replace(/\\'/g, "'");
      const at = chords.findIndex((c) => c.key === after);
      const offset = placed.get(after) ?? 0;
      chords.splice(at === -1 ? chords.length : at + 1 + offset, 0, { key: m[2].replace(/\\'/g, "'"), topic: m[3], does: m[4].replace(/\\'/g, "'") });
      placed.set(after, offset + 1);
    }
  }
  return chords;
}

/** Renders the reference. */
export function keysDoc_render(chords) {
  const topics = [...new Set(chords.map((c) => c.topic))];
  const titles = { pane: 'The pane', focus: 'Focus', binding: 'The next split', claim: 'An empty pane', stage: 'The stage', console: 'The console' };
  const lines = [
    '= ARGUS keys',
    ':toc:',
    '',
    'GENERATED by `node scripts/keys-doc.mjs` from `DRAWER_CHORDS` in `apps/argus/src/console/argusLang.ts`. Do not edit by hand: `npm run lint:aegis` fails when this file and the table disagree.',
    '',
    'Ctrl-B is the prefix: it opens the focused pane\'s drawer with keyboard focus on its first verb. With the drawer open, one key presses one of its capsules (the chords below); Tab walks the verbs, Enter fires, Esc closes. A key typed into a line is never a chord. `argus keys` prints this table in the console; the dashboard\'s HELP tile and `help pane` open it as a pane.',
    '',
  ];
  for (const topic of topics) {
    lines.push(`== ${titles[topic] ?? topic}`, '', '[cols="1,4",options="header"]', '|===', '| Key | Does');
    for (const chord of chords.filter((c) => c.topic === topic)) lines.push(`| \`${chord.key.replace(/\|/g, '\\|')}\` | ${chord.does}`);
    lines.push('|===', '');
  }
  return lines.join('\n');
}

const text = readFileSync(SOURCE, 'utf8');
const rendered = keysDoc_render(chords_read(text));
if (process.argv.includes('--check')) {
  let current = '';
  try { current = readFileSync(TARGET, 'utf8'); } catch { current = ''; }
  if (current !== rendered) {
    console.error(`${TARGET} is out of date with DRAWER_CHORDS; run: node scripts/keys-doc.mjs`);
    process.exit(1);
  }
  console.log(`keys-doc: ${TARGET} matches DRAWER_CHORDS`);
} else {
  writeFileSync(TARGET, rendered);
  console.log(`keys-doc: wrote ${TARGET}`);
}
